package heroes

var DefaultHeroTemplate = []CharacterTemplate{
	{
		Name:           "Imperial Commander",
		CharacterCode:  "imperial_commander",
		AttackPower:    7,
		HealthPoints:   450,
		AttackCooldown: 2,
		Ability: AbilitySpec{
			Code:     BUFF_ATK,
			CoolDown: 3,
			ManaCost: 2,
			Value:    10,
			Duration: 3,
		},
		Description: "Раз в 3 хода повышает урон на 10 любой карты. Баф длится 3 хода",
	},
	{
		Name:           "Karn",
		CharacterCode:  "karn",
		AttackPower:    10,
		HealthPoints:   850,
		AttackCooldown: 3,
		Ability: AbilitySpec{
			Code:     MAKE_TANK,
			CoolDown: 5,
			ManaCost: 5,
			Value:    0,
			Duration: 3,
		},
		Description: "Раз в 5 ходов делает из обычной карты танка. Баф длится 3 хода",
	},
	{
		Name:           "The System",
		CharacterCode:  "the_system",
		AttackPower:    3,
		HealthPoints:   650,
		AttackCooldown: 1,
		Ability: AbilitySpec{
			Code:     ATTACK_ANY,
			CoolDown: 3,
			ManaCost: 3,
			Value:    4,
			Duration: 0,
		},
		Description: "Раз в три хода запускает ракеты, поражая цель и соседей на 4 урона",
	},
	{
		Name:           "Black Cell",
		CharacterCode:  "black_cell",
		AttackPower:    6,
		HealthPoints:   370,
		AttackCooldown: 1,
		Ability: AbilitySpec{
			Code:     BUFF_ATK_PERM,
			Target:   OWN_UNIT,
			CoolDown: 2,
			ManaCost: 2,
			Value:    10,
			Duration: 0,
		},
		Description: "Каждые 2 хода повышает атаку карты на 10 едениц навсегда, но здороввье такой карты всегда равно 1",
	},
	{
		Name:           "Slavic Priest",
		CharacterCode:  "slavic_priest",
		AttackPower:    5,
		HealthPoints:   470,
		AttackCooldown: 3,
		Ability: AbilitySpec{
			Code:     HEAL_UNIT,
			Target:   OWN_UNIT,
			CoolDown: 2,
			ManaCost: 3,
			Value:    10,
			Duration: 0,
		},
		Description: "Каждые 2 хода лечит одну карту на 10",
	},
	{
		Name:           "Supreme Lider",
		CharacterCode:  "suprime_lider",
		AttackPower:    8,
		HealthPoints:   690,
		AttackCooldown: 3,
		Ability: AbilitySpec{
			Code:     ATTACK_ANY,
			Target:   ENEMY_ANY,
			CoolDown: 3,
			ManaCost: 5,
			Value:    30,
			Duration: 0,
		},
	},
}
