package heroes

import "TheWar/internal/domain/cards"

//По примеру с картами, это дефолтный темплейт всех персонажей, которые представлены в игре

//здесь идет перечисление всех персов, их характеристики, имена, и абилки
var DefaultHeroTemplate = []CharacterTemplate{
	{
		Name:           "Имперский командир",
		CharacterCode:  "imperial_commander",
		AttackPower:    4,
		HealthPoints:   60,
		AttackCooldown: 2,
		SplashRadius:   0,
		Ability: AbilitySpec{
			Name:         "Военная машина",
			Code:         "war_machine",
			Description:  "Раз в 3 хода оказывает внушительную поддержку союзной карте, поднимая ее характеристики атаки и ХП на 3 еденицы",
			Kind:         cards.SkillKindBuff,
			Target:       cards.SkillTargetAllySingle,
			CoolDown:     3,
			ManaCost:     3,
			Power:        3,
			Duration:     0,
			ExtraValue:   3,
			ApplyCount:   0,
			BuffEffect:   cards.BuffEffectAttackAndHP,
			DebuffEffect: cards.DebuffEffectNone,
			IgnoreTank:   false,
		},
		Description:    "Генерал Диметриус. Он был первым кто встретился с веспидами на границах империи, лично принимав участие в отражении атаки. Потерял глаз в бою с Карном, когда пытался закрыть портал. Удостоен звания героя Империи как первый, кто принял удар",
		ImageKey:       "",
		AssetBaseKey:   "",
		SkillImageKey:  "",
		AttackImageKey: "",
	},
	{
		//далее по образу и подобию
		Name:           "Карн",
		CharacterCode:  "karn",
		AttackPower:    3,
		HealthPoints:   60,
		AttackCooldown: 1,
		SplashRadius:   0,
		Ability: AbilitySpec{
			Name:         "Первобытная ярость",
			Code:         "primal_rage",
			Description:  "Наносит дебаф группе вражеских войск, наносящий 3 еденицы урона в течении 3х ходов",
			Kind:         cards.SkillKindDebuff,
			Target:       cards.SkillTargetEnemySplash,
			CoolDown:     3,
			ManaCost:     2,
			Power:        3,
			Duration:     3,
			ExtraValue:   0,
			ApplyCount:   1,
			BuffEffect:   cards.BuffEffectNone,
			DebuffEffect: cards.DebuffEffectDamageOverTime,
			IgnoreTank:   true,
		},
		Description:    "Один из сильнейших подпидов веспид. Быстрый, проворный и очень опасный в открытом бою противник. Старики говорили, что их старики говорили что именно этот вид первым ступил на землю",
		ImageKey:       "",
		AssetBaseKey:   "",
		SkillImageKey:  "",
		AttackImageKey: "",
	},
	{
		Name:           "Нейро-Лиск",
		CharacterCode:  "the_system",
		AttackPower:    2,
		HealthPoints:   80,
		AttackCooldown: 1,
		SplashRadius:   0,
		Ability: AbilitySpec{
			Name:         "Защита роя",
			Code:         "swarm_defense",
			Description:  "Раз в 3 хода навсегда делает из обычной карты танка",
			Kind:         cards.SkillKindBuff,
			Target:       cards.SkillTargetAllySingle,
			CoolDown:     3,
			ManaCost:     3,
			Power:        0,
			Duration:     0,
			ExtraValue:   0,
			ApplyCount:   1,
			BuffEffect:   cards.BuffEffectMakeTank,
			DebuffEffect: cards.DebuffEffectNone,
			IgnoreTank:   false,
		},
		Description:    "Доподленно неизвестно что это за подвид. Однако он как то связан с контролем разума других подвидов, заставляя их любой ценой защищать рой. В бою не опасен, однако обладает неопознанной психической силой. Изучение вида результатов не дало",
		ImageKey:       "",
		AssetBaseKey:   "",
		SkillImageKey:  "",
		AttackImageKey: "",
	},
	{
		Name:           "Капитан Мирн",
		CharacterCode:  "black_cell",
		AttackPower:    4,
		HealthPoints:   50,
		AttackCooldown: 1,
		SplashRadius:   0,
		Ability: AbilitySpec{
			Name:         "Выдающийся стрелок",
			Code:         "outstanding_marksman",
			Description:  "Раз в ход атакует противника, нанося ему 3 еденицы урона",
			Kind:         cards.SkillKindDamage,
			Target:       cards.SkillTargetEnemySingle,
			CoolDown:     1,
			ManaCost:     2,
			Power:        3,
			Duration:     0,
			ExtraValue:   0,
			ApplyCount:   1,
			BuffEffect:   cards.BuffEffectNone,
			DebuffEffect: cards.DebuffEffectNone,
			IgnoreTank:   false,
		},
		Description:    "Капитан корпуса стражей, прославившийся в боях за Рокт 5, сектора Юг 3. Порой эгоизм на поле боя дает свои плоды. Записи из личного дела неполны, однако известно, что до службы в корпусе стражей служил в Черной Тысяче",
		ImageKey:       "",
		AssetBaseKey:   "",
		SkillImageKey:  "",
		AttackImageKey: "",
	},
	{
		Name:          "Электро-Жрец",
		CharacterCode: "slavic_priest",
		AttackPower:   4,
		HealthPoints:  60,
		SplashRadius:  1,
		Ability: AbilitySpec{
			Name:         "Мастерство молнии",
			Code:         "lightning_mastery",
			Description:  "Раз в 5 ходов оглушает группу вражеских войск, лишая возможности атаковать и применять способности на 1 ход",
			Kind:         cards.SkillKindDebuff,
			Target:       cards.SkillTargetEnemySplash,
			CoolDown:     5,
			ManaCost:     4,
			Power:        0,
			Duration:     1,
			ExtraValue:   0,
			ApplyCount:   1,
			BuffEffect:   cards.BuffEffectNone,
			DebuffEffect: cards.DebuffEffectStun,
			IgnoreTank:   false,
		},
		Description:    "Был отдан в учение к электро-жрецам еще в юности. За годы обучения прошел полный цикл внедрения протезов в свое тело, став по сути чистым проводником. Участвовал в боях за НовоГранск 5, сектора Идда 1, где и впервые закрыл портал Веспидов. Возглавляет корпус боевых жрецов",
		ImageKey:       "",
		AssetBaseKey:   "",
		SkillImageKey:  "",
		AttackImageKey: "",
	},
	{
		Name:           "Убер-Фекс",
		CharacterCode:  "suprime_lider",
		AttackPower:    4,
		HealthPoints:   65,
		AttackCooldown: 1,
		SplashRadius:   1,
		Ability: AbilitySpec{
			Name:         "Органическое изменение",
			Code:         "organic_change",
			Description:  "Раз в 3 хода навсегда поднимает силу атаки союзной карты на 7 едениц, однако опускает ХП карты на 1",
			Kind:         cards.SkillKindHybrid,
			Target:       cards.SkillTargetAllySingle,
			CoolDown:     3,
			ManaCost:     2,
			Power:        7,
			Duration:     0,
			ExtraValue:   1,
			ApplyCount:   1,
			BuffEffect:   cards.BuffEffectAttack,
			DebuffEffect: cards.DebuffEffectNone,
			IgnoreTank:   false,
		},
		Description:    "Опаснейший вид веспидов, обладающий до сих пор неизвестной магией, позволяющий изменять структуру любого из подвидов. За сотни лет войны так и не удалось изучить не одну особь. Считается самым опасным видом",
		ImageKey:       "",
		AssetBaseKey:   "",
		SkillImageKey:  "",
		AttackImageKey: "",
	},
}
