package cards

/*Описание дефолтных карт. В будущем будут и донатные, но сейчас речь не об этом. Здесь в общем то сердце
всех карт, которые были, есть и будут. Как уже говорилось в описании констант, у каждой карты есть свое
уникальное имя, код (для операционки), хп, атака и все то, что увидишьт внутри описания. Так вот, важно
здесь не то, что и ежу понятно (в роли атаки, хп), а такие штуки как BuffSlot->который отвечает за то, можно
ли улучшить карту, MaxCopies->который отвечает за то, сколько карт конкретного типа можно взять в матч.
Сделано чисто на тот вариант, чтобы игрок не мог с собой взять все 20 карт одной и той же масти, если можно
так сказать конечно. К слову это и сидится вместе с миграциями в моем замечательном пакете bootstrap.*/

/*
В игре представлены (пока что) 3 расы: Империя, Демоны и ИИ технологии. Есть так же три категории карт:
Треш(множественные карты, которые играются массово, они дешевые и не наносят большой урон, так же как и
не обладают большим количеством ХП), Средние карты (Серьезные боевые карты под ту. Обладают хорошими
характеристиками. Стоят средне. В общем, средняя боевая еденица на поле боя) и Ультимативные (самые дорогие
карты в игре(так же карта может быть средней по стоимости, но быть энивей ультимативной). Такие карты имеют
самые крутые статы, но и стоят лошадиных денег)
*/

var DefaultBattleCards = []BattleCardTemplate{
	{
		//обычные чуваки
		Name:              "Стрелковый взвод",
		CodeString:        "rifle_platoon",
		HealthPoints:      5,
		Attack:            3,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          1,
		MaxCopies:         5,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Осколочные гранаты",
		SkillCode:         "fragmentation_grenades",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemySplash,
		SkillPower:        6,
		SkillBaseCooldown: 3,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectNone,
		SkillDebuffEffect: DebuffEffectNone,
		SkillCleanseMode:  CleanseModeNone,
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		//чуваки с драбашами
		Name:              "Отряд зачистки",
		CodeString:        "cleanup_squad",
		Description:       "string",
		HealthPoints:      6,
		Attack:            2,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          1,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Экспансивные снаряды",
		SkillCode:         "expansive_projectiles",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        3,
		SkillBaseCooldown: 5,
		SkillDuration:     2,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectAttack,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		//чувак с огнеметом
		Name:              "Огнеметчик",
		CodeString:        "flamethrowers",
		Description:       "",
		HealthPoints:      2,
		Attack:            4,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          2,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Выжигание",
		SkillCode:         "burning",
		SkillKind:         SkillKindDebuff,
		SkillTargeting:    SkillTargetEnemySingle,
		SkillPower:        2,
		SkillBaseCooldown: 5,
		SkillDuration:     2,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: DebuffEffectDamageOverTime,
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		//челы с гранатометами
		Name:              "Гранатометчики",
		CodeString:        "grenade_launchers",
		Description:       "",
		HealthPoints:      4,
		Attack:            6,
		SplashRadius:      1,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      2,
		ManaCost:          2,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Срочная перезарядка",
		SkillCode:         "urgent_reload",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        1,
		SkillBaseCooldown: 5,
		SkillDuration:     1,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectAttackCooldown,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		//пулеметчики
		Name:              "Пулеметное отделение",
		CodeString:        "machine_gun_section",
		Description:       "Раз в 3 хода может ударить противника дважды",
		HealthPoints:      5,
		Attack:            3,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          3,
		MaxCopies:         5,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Подавление",
		SkillCode:         "suppression",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        0,
		SkillBaseCooldown: 3,
		SkillDuration:     1,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectOverdrive,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		//челы с ядами
		Name:              "Хим отделение",
		CodeString:        "chemical_group",
		Description:       "Раз в 2 хода заражает смертельными ядами вражескую группу",
		HealthPoints:      3,
		Attack:            3,
		SplashRadius:      1,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      2,
		ManaCost:          4,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Заражение патогенами",
		SkillCode:         "infection_with_pathogens",
		SkillKind:         SkillKindDebuff,
		SkillTargeting:    SkillTargetEnemySplash,
		SkillPower:        2,
		SkillBaseCooldown: 2,
		SkillDuration:     1,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: DebuffEffectAttackDown,
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		Name:              "Тяжелый пулеметчик",
		CodeString:        "heavy_machine_gunner",
		Description:       "",
		HealthPoints:      5,
		Attack:            6,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          4,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Второе дыхание",
		SkillCode:         "second_wind",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemySingle,
		SkillPower:        3,
		SkillBaseCooldown: 4,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		Name:              "Артиллерия",
		CodeString:        "artillery",
		Description:       "Запрещает цели атаковать на 2 хода",
		HealthPoints:      3,
		Attack:            6,
		SplashRadius:      1,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      2,
		ManaCost:          4,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Математическая точность",
		SkillCode:         "mathematical_accuracy",
		SkillKind:         SkillKindDebuff,
		SkillTargeting:    SkillTargetEnemySingle,
		SkillPower:        0,
		SkillBaseCooldown: 5,
		SkillDuration:     2,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: DebuffEffectDisarm,
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		//ПОЛЕВОЙ ОФИЦЕР
		Name:              "Поелвой офицер",
		CodeString:        "field_officer",
		Description:       "Снижает КД атаки всему союзному столу",
		HealthPoints:      3,
		Attack:            2,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          4,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Железная воля",
		SkillCode:         "iron_will",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetAllyAll,
		SkillPower:        5,
		SkillBaseCooldown: 5,
		SkillDuration:     3,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectHP,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		// ЗАМЫКАТЕЛЬ. Типа электро маг, который пиздится на ближней дистанции. Очень сильный баф на себя
		//(Электрическая цепь (удар отскакивает в случайного противника, или героя))
		Name:              "Замыкатель",
		CodeString:        "closer",
		Description:       "",
		HealthPoints:      4,
		Attack:            6,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          4,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Цепная индукция",
		SkillCode:         "chain_induction",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        0,
		SkillBaseCooldown: 2,
		SkillDuration:     1,
		SkillExtraValue:   1,
		SkillBuffEffect:   BuffEffectChainAttack,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		//РЕФЛЕКТОР. Самый дешевый танк империи. СКИЛЛ-ЭНЕРГЕТИЧЕСКИЙ РЕТРАНСЛЯТОР(накладывает на себя или союзника отражающий урон щит)
		Name:              "Рефлектор",
		CodeString:        "reflector",
		Description:       "Накладывает на себя, или союзную цель отражающий щит 4/2",
		HealthPoints:      5,
		Attack:            2,
		SplashRadius:      1,
		IsTank:            true,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          4,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Энергетический ретранслятор",
		SkillCode:         "energy_repeater",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetAllySingle,
		SkillPower:        4,
		SkillBaseCooldown: 3,
		SkillDuration:     2,
		SkillExtraValue:   2,
		SkillBuffEffect:   BuffEffectReflectShield,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		//ЕБНУТЫЙ МАГ. АКТИВНЫЙ СКИЛЛ-МАТЕРИАЛЬНОЕ ЭЛЕКТРИЧЕСТВО(бьет электричеством все поле противника)
		Name:              "Архитектор",
		CodeString:        "architect",
		Description:       "Наносит урон всему вражескому столу",
		HealthPoints:      6,
		Attack:            3,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          6,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Материализованная энергия",
		SkillCode:         "materialized_energy",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemyAll,
		SkillPower:        5,
		SkillBaseCooldown: 3,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		Name:              "Тяжелые штурмовики",
		CodeString:        "heavy_stormtroopers",
		Description:       "Раз в 2 хода атакует вражескую цель, у которой больше всего здоровья",
		HealthPoints:      6,
		Attack:            5,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Human,
		BaseCooldown:      2,
		ManaCost:          6,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Давление",
		SkillCode:         "pressure",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemyHighestHP,
		SkillPower:        3,
		SkillBaseCooldown: 2,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		//ОЧЕНЬ СИЛЬНЫЙ СОЛО ТАРГЕТ КАРТА. АКТИВНЫЙ СКИЛЛ-В СЕРДЦЕ(наносит огромный урон в соло цель)
		Name:              "Имперский снайпер",
		CodeString:        "imperial_sniper",
		Description:       "Уничтожает вражескую цель",
		HealthPoints:      5,
		Attack:            7,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      2,
		ManaCost:          6,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Ликвидация",
		SkillCode:         "liquidation",
		SkillKind:         SkillKindKill,
		SkillTargeting:    SkillTargetEnemySingle,
		SkillPower:        0,
		SkillBaseCooldown: 10,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		//ТАЙНЫЙ УБИЙЦА. СКИЛЛ-УДАР ИЗ ТЕНИ(станит цель на Х ходов)
		Name:              "Призрак",
		CodeString:        "ghost",
		Description:       "Оглушает вражескую карту на 2 хода",
		HealthPoints:      5,
		Attack:            5,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      0,
		ManaCost:          5,
		MaxCopies:         4,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Удар из тени",
		SkillCode:         "shadow_strike",
		SkillKind:         SkillKindDebuff,
		SkillTargeting:    SkillTargetEnemySingle,
		SkillPower:        0,
		SkillBaseCooldown: 4,
		SkillDuration:     2,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: DebuffEffectStun,
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		//МАСТЕР БЛИЖНЕГО БОЯ. АКТИВНЫЙ СКИЛЛ-ГЛУБОКИЕ РАНЫ(наносит доту на хп цели на Х ходов)
		Name:              "Фантом",
		CodeString:        "phantom",
		Description:       "Наносит глубокие раны противнику на 3 хода",
		HealthPoints:      5,
		Attack:            6,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          6,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Глубокие раны",
		SkillCode:         "deep_wounds",
		SkillKind:         SkillKindDebuff,
		SkillTargeting:    SkillTargetEnemySingle,
		SkillPower:        4,
		SkillBaseCooldown: 5,
		SkillDuration:     3,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: DebuffEffectDamageOverTime,
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		//КОМАНДРИ ТЯЖЕЛОЙ ПЕХОТЫ. АКТИВНЫЙ СКИЛЛ-ЯРОСТЬ(наносит 3 удара клинком случайным противникам)
		Name:              "Имперерский коммандант",
		CodeString:        "imperial_commandant",
		Description:       "Наносит 3 удара случайным противникам",
		HealthPoints:      8,
		Attack:            5,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          6,
		MaxCopies:         1,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Ярость",
		SkillCode:         "fury",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemyRandomMulti,
		SkillPower:        3,
		SkillBaseCooldown: 3,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   3,
	},
	{
		//ЕБАНУТЫЙ ВОИН С ОГРОМНЫМ МОЛОТОМ. АКТИВНЫЙ СКИЛЛ-БЕЗСТРАШИЕ(наносит урон самой крупной по атаке цели)
		Name:              "Арбитр",
		CodeString:        "arbitrator",
		Description:       "",
		HealthPoints:      10,
		Attack:            7,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Human,
		BaseCooldown:      2,
		ManaCost:          7,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Безстрашие",
		SkillCode:         "fearlessness",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemyHighestAttack,
		SkillPower:        5,
		SkillBaseCooldown: 2,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   true,
		SkillApplyCount:   0,
	},
	{
		//ТАКОЙ ЖЕ ЕБАНУТЫЙ ВОИН, ТОЛЬКО С ОРУЖИЕМ ДАЛЬНЕГО БОЯ. АКТИВНЫЙ СКИЛЛ-НЕПРЕРЫВНЫЙ ОГОНЬ(снижает силу атаки вражескому столу)
		Name:              "Каратель",
		CodeString:        "punisher",
		Description:       "",
		HealthPoints:      7,
		Attack:            8,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      2,
		ManaCost:          7,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Непрерывная битва",
		SkillCode:         "continuous_battle",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        0,
		SkillBaseCooldown: 3,
		SkillDuration:     1,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectOverdrive,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		//ГЛАВНЫЙ СРЕДИ ВСЕЙ ПЕХОТЫ. АКТИВНЫЙ СКИЛЛ-ГЛАВЕНСТВО(существенно поднимает силу атаки ближайшим союзникам)
		Name:              "Архонт",
		CodeString:        "archon",
		Description:       "",
		HealthPoints:      10,
		Attack:            8,
		SplashRadius:      1,
		IsTank:            true,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          9,
		MaxCopies:         1,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Главенство",
		SkillCode:         "headship",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetAllyAdjacent,
		SkillPower:        6,
		SkillBaseCooldown: 5,
		SkillDuration:     4,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectAttack,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		//СРЕДНЯЯ АРТА. АКТИВНЫЙ СКИЛЛ-ФОСФОРНЫЕ СНАРЯДЫ(накладывает аое дот на хп)
		Name:              "Самоходная артиллерия",
		CodeString:        "self_propelled_artillery",
		Description:       "Раз в 5 ходов может атаковать группу противников, накладывая временный урон",
		HealthPoints:      7,
		Attack:            6,
		SplashRadius:      1,
		IsTank:            false,
		CardType:          Mechanical,
		BaseCooldown:      3,
		ManaCost:          4,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Фосфорные снаряды",
		SkillCode:         "phosphorus_shells",
		SkillKind:         SkillKindDebuff,
		SkillTargeting:    SkillTargetEnemySplash,
		SkillPower:        3,
		SkillBaseCooldown: 5,
		SkillDuration:     2,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: DebuffEffectDamageOverTime,
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		//ЕБАНУТО БОЛЬШОЙ ТАНК. АКТИВНЫЙ СКИЛЛ-ЭКСТРЕННЫЕ МЕРЫ(забирает у себя 1 текущего хп, но прибавляет 1 к атаке навсегда)
		Name:              "Малыш",
		CodeString:        "baby",
		Description:       "",
		HealthPoints:      10,
		Attack:            5,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Mechanical,
		BaseCooldown:      1,
		ManaCost:          7,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "",
		SkillCode:         "",
		SkillKind:         "",
		SkillTargeting:    "",
		SkillPower:        0,
		SkillBaseCooldown: 0,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		//ЛЕГКИЙ,МАССОВЫЙ ТАНК ИМПЕРИИ. АКТИВНЫЙ СКИЛЛ-ПОДКРЕПЛЕНИЕ(ставит на стол свою копию)
		Name:              "Вепрь",
		CodeString:        "boar",
		Description:       "",
		HealthPoints:      5,
		Attack:            3,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Mechanical,
		BaseCooldown:      2,
		ManaCost:          5,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Работа в группе",
		SkillCode:         "group_work",
		SkillKind:         SkillKindSummon,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        0,
		SkillBaseCooldown: 8,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   1,
	},
	{
		//КАРТА ЧИСТО ОТ СКИЛА ИГРАЮЩАЯ. АКТИВНЫЙ СКИЛЛ-РАКЕТНОЕ НАВЕДЕНИЕ(выпускает ракету в случайного соло противника)
		Name:              "Установка: ЛИВЕНЬ",
		CodeString:        "system_liven",
		Description:       "Раз в ход может выпустить ракету на 3 урона в случайную цель",
		HealthPoints:      5,
		Attack:            4,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Mechanical,
		BaseCooldown:      3,
		ManaCost:          5,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Ракетное наведение",
		SkillCode:         "missile_guidance",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemyRandom,
		SkillPower:        3,
		SkillBaseCooldown: 1,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   true,
		SkillApplyCount:   0,
	},
	{
		//БТР,КОТОРАЯ ВЕЗЕТ В СЕБЕ ТИПА ЛЮДЕЙ, НО И ПИЗДИТЬСЯ УМЕЕТ. АКТИВНЫЙ СКИЛЛ-ПОПОЛНЕНИЕ(хилит карту-человека)
		Name:              "Волкодав",
		CodeString:        "wolfhound",
		Description:       "Восполняет запас здоровья выбранной цели на 3",
		HealthPoints:      5,
		Attack:            3,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Mechanical,
		BaseCooldown:      1,
		ManaCost:          5,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Пополнение",
		SkillCode:         "replenishment",
		SkillKind:         SkillKindHeal,
		SkillTargeting:    SkillTargetAllySingle,
		SkillPower:        3,
		SkillBaseCooldown: 2,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		//ДАЛЕЕ ВЕСПИДЫ
		Name:              "Мутациды",
		CodeString:        "mutacides",
		Description:       "Призывают на поле боя свою копию",
		HealthPoints:      2,
		Attack:            2,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      1,
		ManaCost:          1,
		MaxCopies:         5,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Рой",
		SkillCode:         "roy",
		SkillKind:         SkillKindSummon,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        0,
		SkillBaseCooldown: 4,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   1,
	},
	{
		Name:              "Омнициды",
		CodeString:        "omnicides",
		Description:       "Наносит ужасающие раны, нанося переодический урон противнику",
		HealthPoints:      3,
		Attack:            3,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      1,
		ManaCost:          1,
		MaxCopies:         5,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Открытые раны",
		SkillCode:         "open_wounds",
		SkillKind:         SkillKindDebuff,
		SkillTargeting:    SkillTargetEnemySingle,
		SkillPower:        2,
		SkillBaseCooldown: 3,
		SkillDuration:     2,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: DebuffEffectDamageOverTime,
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		Name:              "Хексиды",
		CodeString:        "hecksides",
		Description:       "Взрываются атакуя противника",
		HealthPoints:      2,
		Attack:            1,
		SplashRadius:      1,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      1,
		ManaCost:          1,
		MaxCopies:         5,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Взрыв плазмы",
		SkillCode:         "plasma_explosion",
		SkillKind:         SkillKindExplode,
		SkillTargeting:    SkillTargetEnemySplash,
		SkillPower:        4,
		SkillBaseCooldown: 2,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		Name:              "Акрациды",
		CodeString:        "acracides",
		Description:       "Раз в 3 хода исцеляет себя на 2",
		HealthPoints:      5,
		Attack:            1,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Demonical,
		BaseCooldown:      1,
		ManaCost:          1,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Регенерация",
		SkillCode:         "regeneration",
		SkillKind:         SkillKindHeal,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        2,
		SkillBaseCooldown: 3,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		Name:              "Террациды",
		CodeString:        "terracides",
		Description:       "Наносят 3 урона противнику",
		HealthPoints:      4,
		Attack:            3,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      2,
		ManaCost:          3,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Потрошение",
		SkillCode:         "gutting",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemySingle,
		SkillPower:        3,
		SkillBaseCooldown: 2,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		Name:              "Склероцид",
		CodeString:        "sclerocide",
		Description:       "Увеличивает себе максимальное ХП на 2 на 3 хода",
		HealthPoints:      4,
		Attack:            2,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Demonical,
		BaseCooldown:      1,
		ManaCost:          4,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Укрепление панциря",
		SkillCode:         "strengthening_the_shell",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        2,
		SkillBaseCooldown: 1,
		SkillDuration:     3,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectHP,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		Name:              "Веномы",
		CodeString:        "venoms",
		Description:       "Атакует случайного противника, нанося ему 4 урона",
		HealthPoints:      4,
		Attack:            2,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      1,
		ManaCost:          4,
		MaxCopies:         5,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Выброс",
		SkillCode:         "emission",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemyRandom,
		SkillPower:        4,
		SkillBaseCooldown: 2,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   true,
		SkillApplyCount:   0,
	},
	{
		Name:              "Некроцид",
		CodeString:        "lesser_necrocide",
		Description:       "Накладывает на себя баф, дающий ему вампиризм на 2 хода",
		HealthPoints:      5,
		Attack:            6,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Demonical,
		BaseCooldown:      2,
		ManaCost:          5,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Пожирание плоти",
		SkillCode:         "flesh_eating",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        50,
		SkillBaseCooldown: 2,
		SkillDuration:     2,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectVampiricStrike,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		Name:              "Рапторы",
		CodeString:        "raptors",
		Description:       "Могут атаковать цель дважды",
		HealthPoints:      4,
		Attack:            4,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      2,
		ManaCost:          5,
		MaxCopies:         5,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Яростный рывок",
		SkillCode:         "furious_dash",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        0,
		SkillBaseCooldown: 2,
		SkillDuration:     1,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectOverdrive,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		Name:              "Бетацид",
		CodeString:        "betacid",
		Description:       "Накладывает на себя отражающий щит 3/4 на 2 хода",
		HealthPoints:      3,
		Attack:            3,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Demonical,
		BaseCooldown:      1,
		ManaCost:          5,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Шипы",
		SkillCode:         "spikes",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        3,
		SkillBaseCooldown: 3,
		SkillDuration:     2,
		SkillExtraValue:   4,
		SkillBuffEffect:   BuffEffectReflectShield,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		Name:              "Сталкеры",
		CodeString:        "stalkers",
		Description:       "атакуют цель с наименьшим количеством ХП, нанося ей 4 урона",
		HealthPoints:      5,
		Attack:            4,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      2,
		ManaCost:          5,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Нечестная схватка",
		SkillCode:         "unfair_fight",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemyLowestHP,
		SkillPower:        4,
		SkillBaseCooldown: 4,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   true,
		SkillApplyCount:   0,
	},
	{
		Name:              "Экзоцид",
		CodeString:        "eczoside",
		Description:       "Наносит 3 удара по 5 урона случайным противникам",
		HealthPoints:      7,
		Attack:            4,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      2,
		ManaCost:          6,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Прирожденный хищник",
		SkillCode:         "natural_born_predator",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemyRandomMulti,
		SkillPower:        5,
		SkillBaseCooldown: 3,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   true,
		SkillApplyCount:   3,
	},
	{
		Name:              "Омецид",
		CodeString:        "omecide",
		Description:       "раз в 2 хода дважды плюется ядом в случайные цели, нанося им по 5 урона в течении 3х ходов",
		HealthPoints:      6,
		Attack:            2,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      2,
		ManaCost:          6,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Ядовитый всплеск",
		SkillCode:         "poisonous_splash",
		SkillKind:         SkillKindDebuff,
		SkillTargeting:    SkillTargetEnemyRandomMulti,
		SkillPower:        5,
		SkillBaseCooldown: 2,
		SkillDuration:     3,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: DebuffEffectDamageOverTime,
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   2,
	},
	{
		Name:              "Мегацид",
		CodeString:        "megacide",
		Description:       "Раз в ход атакует группу вражеских карт, нанося 8 урона центральной цели",
		HealthPoints:      8,
		Attack:            3,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      2,
		ManaCost:          7,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Плазменный луч",
		SkillCode:         "plasma_beam",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemySplash,
		SkillPower:        8,
		SkillBaseCooldown: 1,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		Name:              "Рапид",
		CodeString:        "rapid",
		Description:       "Раз в 2 хода может атаковать еще 2 случайные цели помимо основной",
		HealthPoints:      8,
		Attack:            6,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      1,
		ManaCost:          8,
		MaxCopies:         1,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Дикая охота",
		SkillCode:         "wild_hunt",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        0,
		SkillBaseCooldown: 2,
		SkillDuration:     1,
		SkillExtraValue:   2,
		SkillBuffEffect:   BuffEffectChainAttack,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		Name:              "Слон",
		CodeString:        "slon",
		Description:       "Призывает собственную копию на стол",
		HealthPoints:      9,
		Attack:            3,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Demonical,
		BaseCooldown:      2,
		ManaCost:          9,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Мы-рой",
		SkillCode:         "we_are_swarm",
		SkillKind:         SkillKindSummon,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        0,
		SkillBaseCooldown: 10,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   1,
	},
	{
		Name:              "Хормагат",
		CodeString:        "hormagat",
		Description:       "Раз в 5 ходов увеличивает КД атаки на 3 хода группе вражеских карт",
		HealthPoints:      9,
		Attack:            6,
		SplashRadius:      1,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      1,
		ManaCost:          9,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Деморализующее присутствие",
		SkillCode:         "demoralizing_presence",
		SkillKind:         SkillKindDebuff,
		SkillTargeting:    SkillTargetEnemySplash,
		SkillPower:        3,
		SkillBaseCooldown: 5,
		SkillDuration:     3,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: DebuffEffectCooldownUp,
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		Name:              "Альфалиск",
		CodeString:        "alphalisk",
		Description:       "Навсегда фиксирует ХП выбранного существа на 1",
		HealthPoints:      8,
		Attack:            8,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      2,
		ManaCost:          9,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Шокирующий ужас",
		SkillCode:         "shocking_horror",
		SkillKind:         SkillKindHybrid,
		SkillTargeting:    SkillTargetEnemySingle,
		SkillPower:        0,
		SkillBaseCooldown: 5,
		SkillDuration:     0,
		SkillExtraValue:   1,
		SkillBuffEffect:   EffectSetFixedHP,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		Name:              "Мегалацид",
		CodeString:        "megalacide",
		Description:       "Посе каждой совершенной атаки поднимает себе силу атаки на 2 на 3 хода",
		HealthPoints:      10,
		Attack:            4,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Demonical,
		BaseCooldown:      1,
		ManaCost:          9,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Постоянный рост",
		SkillCode:         "constant_growth",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        2,
		SkillBaseCooldown: 1,
		SkillDuration:     3,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectBonusAfterAttack,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
	},
	{
		Name:              "Левиафан",
		CodeString:        "leviathan",
		Description:       "На 3 хода делает всех противников восприимчивее к урону на 3",
		HealthPoints:      12,
		Attack:            8,
		SplashRadius:      1,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      4,
		ManaCost:          10,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Оглушительный рев",
		SkillCode:         "deafening_roar",
		SkillKind:         SkillKindDebuff,
		SkillTargeting:    SkillTargetEnemyAll,
		SkillPower:        3,
		SkillBaseCooldown: 3,
		SkillDuration:     3,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: DebuffEffectVulnerable,
		SkillCleanseMode:  "",
		SkillIgnoreTank:   true,
		SkillApplyCount:   0,
	},
}

/*По аналогии с картами, это стандартное описание всех возможных бафф карт, которые есть в игре (так же будут платные)
Как ты можешь увидеть здесь все работает по схожему принципу, за исключением того, что у баф карт очевидно не может
быть силы атаки, кд и всего того, что может бить, стрелять и производить действия на поле боя. Так вот...*/
var DefaultBuffCards = []BuffCardsTemplate{}
