package cards

/*Описание дефолтных карт. В будущем будут и донатные, но сейчас речь не об этом. Здесь в общем то сердце
всех карт, которые были, есть и будут. Как уже говорилось в описании констант, у каждой карты есть свое
уникальное имя, код (для операционки), хп, атака и все то, что увидишьт внутри описания. Так вот, важно
здесь не то, что и ежу понятно (в роли атаки, хп), а такие штуки как BuffSlot->который отвечает за то, можно
ли улучшить карту, MaxCopies->который отвечает за то, сколько карт конкретного типа можно взять в матч.
Сделано чисто на тот вариант, чтобы игрок не мог с собой взять все 20 карт одной и той же масти, если можно
так сказать конечно. К слову это и сидится вместе с миграциями в моем замечательном пакете bootstrap.*/

/*
В игре представлены (пока что) 3 расы: Империя, Демоны и ИИ технологии. Есть так же три категории карт:
Треш(множественные карты, которые играются массово, они дешевые и не наносят большой урон, так же как и
не обладают большим количеством ХП), Средние карты (Серьезные боевые карты под ту. Обладают хорошими
характеристиками. Стоят средне. В общем, средняя боевая еденица на поле боя) и Ультимативные (самые дорогие
карты в игре(так же карта может быть средней по стоимости, но быть энивей ультимативной). Такие карты имеют
самые крутые статы, но и стоят лошадиных денег)
*/

var DefaultBattleCards = []BattleCardTemplate{
	{
		//обычные чуваки ..
		Name:              "Стрелковый взвод",
		CodeString:        "rifle_platoon",
		Description:       "Бросает во врага осколочные гранаты, нанося 2 единицы урона центральной цели",
		HealthPoints:      3,
		Attack:            1,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          1,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Осколочные гранаты",
		SkillCode:         "fragmentation_grenades",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemySplash,
		SkillPower:        2,
		SkillBaseCooldown: 4,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectNone,
		SkillDebuffEffect: DebuffEffectNone,
		SkillCleanseMode:  CleanseModeNone,
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Слаженные действия",
			Code:           "coordinated_actions",
			Description:    "Пока карта жива, рядом стоящие союзные карты люди получают +1 к атаке",
			Kind:           PassiveKindAura,
			Trigger:        PassiveTriggerWhileAlive,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetAllyAdjacent,
			TargetRace:     Human,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttack,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			IgnoreTank:     true,
		},
	},
	{
		//чуваки с драбашами ...
		Name:              "Отряд зачистки",
		CodeString:        "cleanup_squad",
		Description:       "Повышают свою силу атаки на 2 еденицы урона на 3 хода",
		HealthPoints:      4,
		Attack:            1,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          1,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Экспансивные снаряды",
		SkillCode:         "expansive_projectiles",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        2,
		SkillBaseCooldown: 5,
		SkillDuration:     2,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectAttack,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Совершенство тактики",
			Code:           "perfection_of_tactics",
			Description:    "Получает +1 к атаке на 2 хода, когда вражеская карта умирает",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnEnemyDeath,
			Target:         SkillTargetSelf,
			EffectKind:     PassiveEffectBuff,
			Power:          1,
			Duration:       2,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttack,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			IgnoreTank:     true,
		},
	},
	{
		//чувак с огнеметом ...
		Name:              "Огнеметчик",
		CodeString:        "flamethrowers",
		Description:       "Выжигает одиночную цель, накладывая на нее дебаф на 2 хода. Каждый ход цель получает 2 еденицы урона",
		HealthPoints:      3,
		Attack:            3,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          2,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Выжигание",
		SkillCode:         "burning",
		SkillKind:         SkillKindDebuff,
		SkillTargeting:    SkillTargetEnemySingle,
		SkillPower:        2,
		SkillBaseCooldown: 5,
		SkillDuration:     2,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: DebuffEffectDamageOverTime,
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Доктринальное выжигание",
			Code:           "doctrinal_burning",
			Description:    "Получает +1 к атаке, когда на союзном столе есть танк",
			Kind:           PassiveKindAura,
			Trigger:        PassiveTriggerWhileAlive,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttack,
			DebuffEffect:   "",
			Condition:      PassiveConditionOwnerHasTank,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			IgnoreTank:     true,
		},
	},
	{
		//челы с гранатометами ...
		Name:              "Гранатометчики",
		CodeString:        "grenade_launchers",
		Description:       "Немедленно заряжает снаряды, уменьшая текущий КД атаки на 1 ход",
		HealthPoints:      4,
		Attack:            3,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      2,
		ManaCost:          2,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Срочная перезарядка",
		SkillCode:         "urgent_reload",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        1,
		SkillBaseCooldown: 5,
		SkillDuration:     1,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectAttackCooldown,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Залп",
			Code:           "barrage",
			Description:    "Когда противник ставит на стол танка, наносит 3 еденицы урона случайной цели",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnEnemyPlay,
			EffectKind:     PassiveEffectDamage,
			Target:         SkillTargetEnemyRandom,
			Power:          3,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     "",
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionValue: 0,
			EventFilter:    PassiveEventFilterCardPlayed,
			EventRace:      "",
			EventIsTank:    true,
			IgnoreTank:     false,
		},
	},
	{
		//пулеметчики ...
		Name:              "Пулеметное отделение",
		CodeString:        "machine_gun_section",
		Description:       "Смена пулеметной ленты позволяет атаковать после атаки",
		HealthPoints:      5,
		Attack:            3,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          3,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Подавление",
		SkillCode:         "suppression",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        0,
		SkillBaseCooldown: 4,
		SkillDuration:     1,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectOverdrive,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Позиционная война",
			Code:           "trench_warfare",
			Description:    "В начале хода получает +1 к атаке",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerTurnStart,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttack,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			EventIsTank:    false,
			IgnoreTank:     true,
		},
	},
	{
		//челы с ядами ...
		Name:              "Хим отделение",
		CodeString:        "chemical_group",
		Description:       "Заражает смертельными ядами вражескую группу, понижая их силу атаки на 2 единицы на 2 хода",
		HealthPoints:      5,
		Attack:            2,
		SplashRadius:      1,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      2,
		ManaCost:          4,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Заражение патогенами",
		SkillCode:         "infection_with_pathogens",
		SkillKind:         SkillKindDebuff,
		SkillTargeting:    SkillTargetEnemySplash,
		SkillPower:        2,
		SkillBaseCooldown: 3,
		SkillDuration:     1,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: DebuffEffectAttackDown,
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Токсичное облако",
			Code:           "toxic_cloud",
			Description:    "В конце хода наносит 1 урон всему вражескому столу",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerTurnEnd,
			EffectKind:     PassiveEffectDamage,
			Target:         SkillTargetEnemyAll,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     "",
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			EventIsTank:    false,
			IgnoreTank:     true,
		},
	},
	{
		/// ...
		Name:              "Тяжелый пулеметчик",
		CodeString:        "heavy_machine_gunner",
		Description:       "Концентрирует огонь, нанося 3 единицы урона противнику",
		HealthPoints:      5,
		Attack:            5,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      2,
		ManaCost:          4,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Второе дыхание",
		SkillCode:         "second_wind",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemySingle,
		SkillPower:        3,
		SkillBaseCooldown: 4,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Отличная позиция",
			Code:           "perfect_position",
			Description:    "В начале хода получает +1 к атаке",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerTurnStart,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttack,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			EventIsTank:    false,
			IgnoreTank:     true,
		},
	},
	{
		// ...
		Name:              "Артиллерия",
		CodeString:        "artillery",
		Description:       "Атакует единичную цель, лишая ее возможности атаковать на следующий ход",
		HealthPoints:      5,
		Attack:            4,
		SplashRadius:      1,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      2,
		ManaCost:          4,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Математическая точность",
		SkillCode:         "mathematical_accuracy",
		SkillKind:         SkillKindDebuff,
		SkillTargeting:    SkillTargetEnemySingle,
		SkillPower:        0,
		SkillBaseCooldown: 5,
		SkillDuration:     2,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: DebuffEffectDisarm,
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Оперативная перезарядка",
			Code:           "rapid_reload_protocol",
			Description:    "Снижает текущий КД атаки каждый раз, когда вы разыгрываете карту техники",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnAllyPlay,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttackCooldown,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  Mechanical,
			ConditionValue: 0,
			EventFilter:    PassiveEventFilterCardPlayed,
			EventRace:      Mechanical,
			IgnoreTank:     true,
		},
	},
	{
		//ПОЛЕВОЙ ОФИЦЕР ...
		Name:              "Поелвой офицер",
		CodeString:        "field_officer",
		Description:       "Повышает ХП на 3 единицы всему союзному столу на 2 хода",
		HealthPoints:      5,
		Attack:            2,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          4,
		MaxCopies:         1,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Железная воля",
		SkillCode:         "iron_will",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetAllyAll,
		SkillPower:        3,
		SkillBaseCooldown: 5,
		SkillDuration:     2,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectHP,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Железная воля",
			Code:           "iron_will",
			Description:    "В начале хода повышает силу атаки всему союзному столу на 1 на 1 ход",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerTurnStart,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetAllyAll,
			Power:          1,
			Duration:       1,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttack,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			IgnoreTank:     true,
		},
	},
	{
		// ЗАМЫКАТЕЛЬ. Типа электро маг, который пиздится на ближней дистанции. Очень сильный баф на себя
		//(Электрическая цепь (удар отскакивает в случайного противника, или героя))
		Name:              "Замыкатель",
		CodeString:        "closer",
		Description:       "Накладывает на себя баф, позволяющий следующей атаке отскочить в случайного противника",
		HealthPoints:      6,
		Attack:            5,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          5,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Цепная индукция",
		SkillCode:         "chain_induction",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        0,
		SkillBaseCooldown: 3,
		SkillDuration:     1,
		SkillExtraValue:   1,
		SkillBuffEffect:   BuffEffectChainAttack,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Мгновенная реакция",
			Code:           "instant_reaction",
			Description:    "Наносит 2 урона случайной вражеской цели, когда герой противника использует способность",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnEnemyHeroSkill,
			EffectKind:     PassiveEffectDamage,
			Target:         SkillTargetEnemyRandom,
			Power:          2,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     "",
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			IgnoreTank:     false,
		},
	},
	{
		//РЕФЛЕКТОР. Самый дешевый танк империи. СКИЛЛ-ЭНЕРГЕТИЧЕСКИЙ РЕТРАНСЛЯТОР(накладывает на себя или союзника отражающий урон щит)
		Name:              "Рефлектор",
		CodeString:        "reflector",
		Description:       "Накладывает на себя, или союзную цель отражающий щит 3/2",
		HealthPoints:      8,
		Attack:            2,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          4,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Энергетический ретранслятор",
		SkillCode:         "energy_repeater",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetAllySingle,
		SkillPower:        3,
		SkillBaseCooldown: 3,
		SkillDuration:     2,
		SkillExtraValue:   2,
		SkillBuffEffect:   BuffEffectReflectShield,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Защитное поле",
			Code:           "protective_field",
			Description:    "Пока карта жива, весь союзный стол получает +1 к ХП",
			Kind:           PassiveKindAura,
			Trigger:        PassiveTriggerWhileAlive,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetAllyAll,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectHP,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			IgnoreTank:     true,
		},
	},
	{
		//ЕБНУТЫЙ МАГ. АКТИВНЫЙ СКИЛЛ-МАТЕРИАЛЬНОЕ ЭЛЕКТРИЧЕСТВО(бьет электричеством все поле противника)
		Name:              "Архитектор",
		CodeString:        "architect",
		Description:       "Наносит 3 урона всему вражескому столу",
		HealthPoints:      6,
		Attack:            3,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          6,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Материализованная энергия",
		SkillCode:         "materialized_energy",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemyAll,
		SkillPower:        3,
		SkillBaseCooldown: 4,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Бесконечная ненависть",
			Code:           "endless_hate",
			Description:    "Увеличивает силу своей способности на 1 каждый раз, когда союзная карта умирает",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnAllyDeath,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectSkillPower,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			IgnoreTank:     true,
		},
	},
	{
		Name:              "Тяжелые штурмовики",
		CodeString:        "heavy_stormtroopers",
		Description:       "Раз в 2 хода атакует вражескую цель, у которой больше всего здоровья, нонося цели 3 единицы урона",
		HealthPoints:      10,
		Attack:            4,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Human,
		BaseCooldown:      2,
		ManaCost:          6,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Давление",
		SkillCode:         "pressure",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemyHighestHP,
		SkillPower:        3,
		SkillBaseCooldown: 3,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "До последней капли крови",
			Code:           "to_the_last_drop",
			Description:    "Повышает свою атаку каждый раз, когда получает урон",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnDamaged,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttack,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			IgnoreTank:     true,
		},
	},
	{
		//ОЧЕНЬ СИЛЬНЫЙ СОЛО ТАРГЕТ КАРТА. АКТИВНЫЙ СКИЛЛ-В СЕРДЦЕ(наносит огромный урон в соло цель)
		Name:              "Имперский снайпер",
		CodeString:        "imperial_sniper",
		Description:       "Уничтожает вражескую цель",
		HealthPoints:      6,
		Attack:            5,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      2,
		ManaCost:          6,
		MaxCopies:         1,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Ликвидация",
		SkillCode:         "liquidation",
		SkillKind:         SkillKindKill,
		SkillTargeting:    SkillTargetEnemySingle,
		SkillPower:        0,
		SkillBaseCooldown: 15,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Постоянное обучение",
			Code:           "constant_training",
			Description:    "В конце хода повышает атаку себе и соседним союзникам на 1",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerTurnEnd,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelfAndAdjacent,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttack,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			IgnoreTank:     true,
		},
	},
	{
		//ТАЙНЫЙ УБИЙЦА. СКИЛЛ-УДАР ИЗ ТЕНИ(станит цель на Х ходов)
		Name:              "Призрак",
		CodeString:        "ghost",
		Description:       "Оглушает вражескую карту на 2 хода",
		HealthPoints:      6,
		Attack:            4,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          5,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Удар из тени",
		SkillCode:         "shadow_strike",
		SkillKind:         SkillKindDebuff,
		SkillTargeting:    SkillTargetEnemySingle,
		SkillPower:        0,
		SkillBaseCooldown: 4,
		SkillDuration:     2,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: DebuffEffectStun,
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Искоренение",
			Code:           "eradication",
			Description:    "Пока на столе противника 3 и больше веспидов, получает +2 к атаке",
			Kind:           PassiveKindAura,
			Trigger:        PassiveTriggerWhileAlive,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          2,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttack,
			DebuffEffect:   "",
			Condition:      PassiveConditionEnemyRaceCount,
			ConditionRace:  Demonical,
			ConditionValue: 3,
			EventFilter:    "",
			EventRace:      "",
			IgnoreTank:     true,
		},
	},
	{
		//МАСТЕР БЛИЖНЕГО БОЯ. АКТИВНЫЙ СКИЛЛ-ГЛУБОКИЕ РАНЫ(наносит доту на хп цели на Х ходов)
		Name:              "Фантом",
		CodeString:        "phantom",
		Description:       "Наносит глубокие раны противнику. Цель получает 3 единицы урона в течении 2х ходов",
		HealthPoints:      7,
		Attack:            4,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          6,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Глубокие раны",
		SkillCode:         "deep_wounds",
		SkillKind:         SkillKindDebuff,
		SkillTargeting:    SkillTargetEnemySingle,
		SkillPower:        3,
		SkillBaseCooldown: 5,
		SkillDuration:     2,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: DebuffEffectDamageOverTime,
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Жажда крови",
			Code:           "blood_thirst",
			Description:    "Получает +1 к атаке за каждую карту на столе противника",
			Kind:           PassiveKindAura,
			Trigger:        PassiveTriggerWhileAlive,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttack,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			ScaleMode:      PassiveScalePerEnemyUnit,
			IgnoreTank:     true,
		},
	},
	{ //-----------------------------------------------------------------------------------------------
		//КОМАНДИР ТЯЖЕЛОЙ ПЕХОТЫ. АКТИВНЫЙ СКИЛЛ-ЯРОСТЬ(наносит 3 удара клинком случайным противникам)
		Name:              "Имперерский коммандант",
		CodeString:        "imperial_commandant",
		Description:       "Наносит 3 удара случайным противникам",
		HealthPoints:      10,
		Attack:            5,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          6,
		MaxCopies:         1,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Ярость",
		SkillCode:         "fury",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemyRandomMulti,
		SkillPower:        3,
		SkillBaseCooldown: 4,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   3,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Личный пример",
			Code:           "lead_by_example",
			Description:    "Каждый раз, когда атакует основной атакой, повышает силу атаки всего союзного стола на 1",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnAttack,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetAllyAll,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttack,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			IgnoreTank:     true,
		},
	},
	{
		//ЕБАНУТЫЙ ВОИН С ОГРОМНЫМ МОЛОТОМ. АКТИВНЫЙ СКИЛЛ-БЕЗСТРАШИЕ(наносит урон самой крупной по атаке цели)
		Name:              "Арбитр",
		CodeString:        "arbitrator",
		Description:       "Наносит 5 едениц урона цели с наибольшим значением атаки",
		HealthPoints:      11,
		Attack:            6,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Human,
		BaseCooldown:      2,
		ManaCost:          7,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Безстрашие",
		SkillCode:         "fearlessness",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemyHighestAttack,
		SkillPower:        5,
		SkillBaseCooldown: 3,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   true,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Ветеран",
			Code:           "veteran",
			Description:    "Каждый раз, когда получает урон, повышает себе атаку и ХП на 1",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnDamaged,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          1,
			Duration:       0,
			ExtraValue:     1,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttackAndHP,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			IgnoreTank:     true,
		},
	},
	{
		//ТАКОЙ ЖЕ ЕБАНУТЫЙ ВОИН, ТОЛЬКО С ОРУЖИЕМ ДАЛЬНЕГО БОЯ. АКТИВНЫЙ СКИЛЛ-НЕПРЕРЫВНЫЙ ОГОНЬ(снижает силу атаки вражескому столу)
		Name:              "Каратель",
		CodeString:        "punisher",
		Description:       "Накладывает на себя баф, позволяющий атаковать дважды",
		HealthPoints:      10,
		Attack:            6,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Human,
		BaseCooldown:      2,
		ManaCost:          7,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Непрерывная битва",
		SkillCode:         "continuous_battle",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        0,
		SkillBaseCooldown: 4,
		SkillDuration:     1,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectOverdrive,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Военная машина",
			Code:           "war_machine",
			Description:    "Каждый раз, когда атакует, повышает себе силу атаки на 1 на 3 хода",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnAttack,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          1,
			Duration:       3,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttack,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			IgnoreTank:     true,
		},
	},
	{
		//ГЛАВНЫЙ СРЕДИ ВСЕЙ ПЕХОТЫ. АКТИВНЫЙ СКИЛЛ-ГЛАВЕНСТВО(существенно поднимает силу атаки ближайшим союзникам)
		Name:              "Архонт",
		CodeString:        "archon",
		Description:       "Накладывает на рядом стоящих союзников баф, повышающий их силу атаки на +4 на 3 хода",
		HealthPoints:      14,
		Attack:            6,
		SplashRadius:      1,
		IsTank:            true,
		CardType:          Human,
		BaseCooldown:      1,
		ManaCost:          9,
		MaxCopies:         1,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Главенство",
		SkillCode:         "headship",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetAllyAdjacent,
		SkillPower:        4,
		SkillBaseCooldown: 5,
		SkillDuration:     3,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectAttack,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Месть человечества",
			Code:           "humanity_revenge",
			Description:    "Каждый раз, когда противник разыгрывает карту, наносит 2 урона случайной вражеской цели",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnEnemyPlay,
			EffectKind:     PassiveEffectDamage,
			Target:         SkillTargetEnemyRandom,
			Power:          2,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     "",
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    PassiveEventFilterCardPlayed,
			EventRace:      "",
			IgnoreTank:     false,
		},
	},
	{
		//СРЕДНЯЯ АРТА. АКТИВНЫЙ СКИЛЛ-ФОСФОРНЫЕ СНАРЯДЫ(накладывает аое дот на хп)
		Name:              "Самоходная артиллерия",
		CodeString:        "self_propelled_artillery",
		Description:       "Заряжает фосфорные снаряды, атакуя группу противников и нанося дебаф на 2 хода, нанося 3 единицы урона за ход",
		HealthPoints:      6,
		Attack:            3,
		SplashRadius:      1,
		IsTank:            false,
		CardType:          Mechanical,
		BaseCooldown:      3,
		ManaCost:          4,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Фосфорные снаряды",
		SkillCode:         "phosphorus_shells",
		SkillKind:         SkillKindDebuff,
		SkillTargeting:    SkillTargetEnemySplash,
		SkillPower:        2,
		SkillBaseCooldown: 5,
		SkillDuration:     2,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: DebuffEffectDamageOverTime,
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Железная поддержка",
			Code:           "iron_support",
			Description:    "Получает +1 к атаке за каждую карту типа Человек на вашем столе",
			Kind:           PassiveKindAura,
			Trigger:        PassiveTriggerWhileAlive,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttack,
			DebuffEffect:   "",
			Condition:      PassiveConditionOwnerRaceCount,
			ConditionRace:  Human,
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			ScaleMode:      PassiveScalePerOwnerRaceCount,
			IgnoreTank:     true,
		},
	},
	{
		//ЕБАНУТО БОЛЬШОЙ ТАНК. АКТИВНЫЙ СКИЛЛ-ЭКСТРЕННЫЕ МЕРЫ(забирает у себя 1 текущего хп, но прибавляет 1 к атаке навсегда)
		Name:              "Малыш",
		CodeString:        "baby",
		Description:       "Эта карта пока ничего не делает",
		HealthPoints:      16,
		Attack:            5,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Mechanical,
		BaseCooldown:      1,
		ManaCost:          8,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          false,
		SkillName:         "",
		SkillCode:         "",
		SkillKind:         "",
		SkillTargeting:    "",
		SkillPower:        0,
		SkillBaseCooldown: 0,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Многотонная надежда",
			Code:           "many_tons_of_hope",
			Description:    "В начале хода повышает атаку и ХП всего союзного стола на 1",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerTurnStart,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetAllyAll,
			Power:          1,
			Duration:       0,
			ExtraValue:     1,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttackAndHP,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			IgnoreTank:     true,
		},
	},
	{
		//ЛЕГКИЙ,МАССОВЫЙ ТАНК ИМПЕРИИ. АКТИВНЫЙ СКИЛЛ-ПОДКРЕПЛЕНИЕ(ставит на стол свою копию)
		Name:              "Вепрь",
		CodeString:        "boar",
		Description:       "Призывает на стол свою копию",
		HealthPoints:      8,
		Attack:            2,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Mechanical,
		BaseCooldown:      2,
		ManaCost:          5,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Работа в группе",
		SkillCode:         "group_work",
		SkillKind:         SkillKindSummon,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        0,
		SkillBaseCooldown: 8,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   1,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Механизированная группа",
			Code:           "mechanized_group",
			Description:    "Получает +1 к атаке за каждую механическую карту на союзном столе",
			Kind:           PassiveKindAura,
			Trigger:        PassiveTriggerWhileAlive,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttack,
			DebuffEffect:   "",
			Condition:      PassiveConditionOwnerRaceCount,
			ConditionRace:  Mechanical,
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			ScaleMode:      PassiveScalePerOwnerRaceCount,
			IgnoreTank:     true,
		},
	},
	{
		//КАРТА ЧИСТО ОТ СКИЛА ИГРАЮЩАЯ. АКТИВНЫЙ СКИЛЛ-РАКЕТНОЕ НАВЕДЕНИЕ(выпускает ракету в случайного соло противника)
		Name:              "Установка: ЛИВЕНЬ",
		CodeString:        "system_liven",
		Description:       "Выпусает ракету, наносащую 3 еденицы урона случайной вражеской цели",
		HealthPoints:      7,
		Attack:            3,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Mechanical,
		BaseCooldown:      3,
		ManaCost:          5,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Ракетное наведение",
		SkillCode:         "missile_guidance",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemyRandom,
		SkillPower:        3,
		SkillBaseCooldown: 2,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   true,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Ответные меры",
			Code:           "countermeasures",
			Description:    "Наносит 2 урона случайной вражеской карте каждый раз, когда вражеская карта использует способность",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnEnemySkill,
			EffectKind:     PassiveEffectDamage,
			Target:         SkillTargetEnemyRandom,
			Power:          2,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     "",
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    PassiveEventFilterSkillUsed,
			EventRace:      "",
			IgnoreTank:     false,
		},
	},
	{
		//БТР,КОТОРАЯ ВЕЗЕТ В СЕБЕ ТИПА ЛЮДЕЙ, НО И ПИЗДИТЬСЯ УМЕЕТ. АКТИВНЫЙ СКИЛЛ-ПОПОЛНЕНИЕ(хилит карту-человека)
		Name:              "Волкодав",
		CodeString:        "wolfhound",
		Description:       "Восполняет запас здоровья выбранной цели на 3 еденицы",
		HealthPoints:      7,
		Attack:            3,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Mechanical,
		BaseCooldown:      1,
		ManaCost:          5,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Пополнение",
		SkillCode:         "replenishment",
		SkillKind:         SkillKindHeal,
		SkillTargeting:    SkillTargetAllySingle,
		SkillPower:        3,
		SkillBaseCooldown: 3,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Срочное пополнение",
			Code:           "urgent_reinforcement",
			Description:    "Каждый раз, когда противник разыгрывает карту, лечит союзную карту типа Человек с наименьшим запасом ХП на 1",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnEnemyPlay,
			Target:         SkillTargetAllyLowestHP,
			EffectKind:     PassiveEffectHeal,
			TargetRace:     Human,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     "",
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    PassiveEventFilterCardPlayed,
			EventRace:      "",
			IgnoreTank:     true,
		},
	},
	{
		//ДАЛЕЕ ВЕСПИДЫ
		Name:              "Мутациды",
		CodeString:        "mutacides",
		Description:       "Призывает на поле боя свою копию",
		HealthPoints:      4,
		Attack:            1,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      1,
		ManaCost:          1,
		MaxCopies:         5,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Рой",
		SkillCode:         "roy",
		SkillKind:         SkillKindSummon,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        0,
		SkillBaseCooldown: 5,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   1,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Единый организм",
			Code:           "single_organism",
			Description:    "Пока на союзном столе 3 и больше карт Веспид, получает +1 к атаке",
			Kind:           PassiveKindAura,
			Trigger:        PassiveTriggerWhileAlive,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttack,
			DebuffEffect:   "",
			Condition:      PassiveConditionOwnerRaceCount,
			ConditionRace:  Demonical,
			ConditionValue: 3,
			EventFilter:    "",
			EventRace:      "",
			IgnoreTank:     true,
		},
	},
	{
		Name:              "Омнициды",
		CodeString:        "omnicides",
		Description:       "Наносит ужасающие раны, наносящие 1 единицу урона за ход в течении 2х ходов",
		HealthPoints:      4,
		Attack:            1,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      1,
		ManaCost:          1,
		MaxCopies:         5,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Открытые раны",
		SkillCode:         "open_wounds",
		SkillKind:         SkillKindDebuff,
		SkillTargeting:    SkillTargetEnemySingle,
		SkillPower:        1,
		SkillBaseCooldown: 4,
		SkillDuration:     2,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: DebuffEffectDamageOverTime,
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Видовая особенность",
			Code:           "species_trait",
			Description:    "Каждый раз, когда атакует, накладывает на цель дебаф на 2 хода, наносящий 1 единицу урона",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnAttack,
			EffectKind:     PassiveEffectDebuff,
			Target:         SkillTargetAttackTarget,
			Power:          1,
			Duration:       2,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     "",
			DebuffEffect:   DebuffEffectDamageOverTime,
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			IgnoreTank:     true,
		},
	},
	{
		Name:              "Хексиды",
		CodeString:        "hecksides",
		Description:       "Наносят 3 единицы урона группе вражеских войск, но сами умирают",
		HealthPoints:      3,
		Attack:            1,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      1,
		ManaCost:          1,
		MaxCopies:         5,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Взрыв плазмы",
		SkillCode:         "plasma_explosion",
		SkillKind:         SkillKindExplode,
		SkillTargeting:    SkillTargetEnemySplash,
		SkillPower:        3,
		SkillBaseCooldown: 2,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Ужасная вонь",
			Code:           "horrible_stench",
			Description:    "Когда получает урон, накладывает на весь вражеский стол дебаф, наносящий 1 единицу урона за ход в течение 2 ходов",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnDamaged,
			EffectKind:     PassiveEffectDebuff,
			Target:         SkillTargetEnemyAll,
			Power:          1,
			Duration:       2,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     "",
			DebuffEffect:   DebuffEffectDamageOverTime,
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			IgnoreTank:     true,
		},
	},
	{
		Name:              "Акрациды",
		CodeString:        "acracides",
		Description:       "Раз в 3 хода может поднять себе ХП на 2",
		HealthPoints:      8,
		Attack:            1,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Demonical,
		BaseCooldown:      1,
		ManaCost:          2,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Регенерация",
		SkillCode:         "regeneration",
		SkillKind:         SkillKindHeal,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        2,
		SkillBaseCooldown: 3,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Эволюция панциря",
			Code:           "shell_evolution",
			Description:    "В конце хода повышает себе ХП на 1",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerTurnEnd,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectHP,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			IgnoreTank:     true,
		},
	},
	{
		Name:              "Террациды",
		CodeString:        "terracides",
		Description:       "Наносят 3 еденицы урона противнику",
		HealthPoints:      7,
		Attack:            2,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      2,
		ManaCost:          3,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Потрошение",
		SkillCode:         "gutting",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemySingle,
		SkillPower:        3,
		SkillBaseCooldown: 3,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Доминация массы",
			Code:           "mass_domination",
			Description:    "Получает +1 к атаке за каждого веспида на союзном столе",
			Kind:           PassiveKindAura,
			Trigger:        PassiveTriggerWhileAlive,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttack,
			DebuffEffect:   "",
			Condition:      PassiveConditionOwnerRaceCount,
			ConditionRace:  Demonical,
			ConditionValue: 0,
			EventFilter:    "",
			EventRace:      "",
			ScaleMode:      PassiveScalePerOwnerRaceCount,
			IgnoreTank:     true,
		},
	},
	{
		Name:              "Склероцид",
		CodeString:        "sclerocide",
		Description:       "Увеличивает себе максимальное количество ХП на 2 еденицы на 3 хода",
		HealthPoints:      10,
		Attack:            2,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Demonical,
		BaseCooldown:      1,
		ManaCost:          4,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Укрепление панциря",
		SkillCode:         "strengthening_the_shell",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        2,
		SkillBaseCooldown: 3,
		SkillDuration:     3,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectHP,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Эволюция клешней",
			Code:           "claw_evolution",
			Description:    "Каждый раз, когда атакует, повышает себе силу атаки на 1",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnAttack,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttack,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    PassiveEventFilterNone,
			EventRace:      "",
			ScaleMode:      PassiveScaleNone,
			IgnoreTank:     true,
		},
	},
	{
		Name:              "Веномы",
		CodeString:        "venoms",
		Description:       "Атакует случайного противника, нанося ему 3 единицы урона",
		HealthPoints:      6,
		Attack:            2,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      1,
		ManaCost:          4,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Выброс",
		SkillCode:         "emission",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemyRandom,
		SkillPower:        3,
		SkillBaseCooldown: 2,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   true,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Старший вид",
			Code:           "elder_species",
			Description:    "Пока карта жива, повышает ХП всего союзного стола",
			Kind:           PassiveKindAura,
			Trigger:        PassiveTriggerWhileAlive,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetAllyAll,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectHP,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    PassiveEventFilterNone,
			EventRace:      "",
			ScaleMode:      PassiveScaleNone,
			IgnoreTank:     true,
		},
	},
	{
		Name:              "Некроцид",
		CodeString:        "lesser_necrocide",
		Description:       "Накладывает на себя баф, дающий ему вампиризм на 2 хода, восстанавливающий ему 50% от нанесенного урона",
		HealthPoints:      8,
		Attack:            4,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Demonical,
		BaseCooldown:      2,
		ManaCost:          5,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Пожирание плоти",
		SkillCode:         "flesh_eating",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        50,
		SkillBaseCooldown: 4,
		SkillDuration:     2,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectVampiricStrike,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Новый биоматериал",
			Code:           "new_biomaterial",
			Description:    "Каждый раз, когда умирает вражеская карта, повышает себе ХП на 1",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnEnemyDeath,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectHP,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    PassiveEventFilterNone,
			EventRace:      "",
			ScaleMode:      PassiveScaleNone,
			IgnoreTank:     true,
		},
	},
	{
		Name:              "Рапторы",
		CodeString:        "raptors",
		Description:       "При активации скилла атакует дважды",
		HealthPoints:      6,
		Attack:            3,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      2,
		ManaCost:          5,
		MaxCopies:         3,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Яростный рывок",
		SkillCode:         "furious_dash",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        0,
		SkillBaseCooldown: 3,
		SkillDuration:     1,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectOverdrive,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Ядовитый всплеск",
			Code:           "poison_burst",
			Description:    "Каждый раз, когда противник разыгрывает карту, накладывает на случайную вражескую цель дебаф на 2 хода, наносящий 1 единицу урона",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnEnemyPlay,
			EffectKind:     PassiveEffectDebuff,
			Target:         SkillTargetEnemyRandom,
			Power:          1,
			Duration:       2,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     "",
			DebuffEffect:   DebuffEffectDamageOverTime,
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    PassiveEventFilterCardPlayed,
			EventRace:      "",
			ScaleMode:      PassiveScaleNone,
			IgnoreTank:     false,
		},
	},
	{
		Name:              "Бетацид",
		CodeString:        "betacid",
		Description:       "Накладывает на себя отражающий щит 3/4 на 2 хода",
		HealthPoints:      9,
		Attack:            3,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Demonical,
		BaseCooldown:      1,
		ManaCost:          5,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Шипы",
		SkillCode:         "spikes",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        3,
		SkillBaseCooldown: 3,
		SkillDuration:     2,
		SkillExtraValue:   4,
		SkillBuffEffect:   BuffEffectReflectShield,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Острые иглы",
			Code:           "sharp_spikes",
			Description:    "Каждый раз, когда получает урон, накладывает на атакующего дебаф на 2 хода, наносящий 1 единицу урона",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnDamaged,
			EffectKind:     PassiveEffectDebuff,
			Target:         SkillTargetAttackTarget,
			Power:          1,
			Duration:       2,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     "",
			DebuffEffect:   DebuffEffectDamageOverTime,
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    PassiveEventFilterNone,
			EventRace:      "",
			ScaleMode:      PassiveScaleNone,
			IgnoreTank:     true,
		},
	},
	{
		Name:              "Сталкеры",
		CodeString:        "stalkers",
		Description:       "Атакуют цель с наименьшим количеством ХП, нанося ей 4 еденицы урона",
		HealthPoints:      8,
		Attack:            3,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      2,
		ManaCost:          5,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Нечестная схватка",
		SkillCode:         "unfair_fight",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemyLowestHP,
		SkillPower:        4,
		SkillBaseCooldown: 4,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   true,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Агрессивный вид",
			Code:           "aggressive_species",
			Description:    "Получает +1 к атаке за каждого танка на столе противника",
			Kind:           PassiveKindAura,
			Trigger:        PassiveTriggerWhileAlive,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttack,
			DebuffEffect:   "",
			Condition:      PassiveConditionEnemyHasTank,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    PassiveEventFilterNone,
			EventRace:      "",
			ScaleMode:      PassiveScalePerEnemyTank,
			IgnoreTank:     true,
		},
	},
	{
		Name:              "Экзоцид",
		CodeString:        "eczoside",
		Description:       "Наносит 3 удара по 4 еденицы урона случайным противникам",
		HealthPoints:      8,
		Attack:            5,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      2,
		ManaCost:          6,
		MaxCopies:         1,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Прирожденный хищник",
		SkillCode:         "natural_born_predator",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemyRandomMulti,
		SkillPower:        4,
		SkillBaseCooldown: 4,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   true,
		SkillApplyCount:   3,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Временная мутация",
			Code:           "temporary_mutation",
			Description:    "Каждый раз, когда вы разыгрываете карту, получает +1 к силе своего скилла",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnAllyPlay,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectSkillPower,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    PassiveEventFilterCardPlayed,
			EventRace:      "",
			ScaleMode:      PassiveScaleNone,
			IgnoreTank:     true,
		},
	},
	{
		Name:              "Омецид",
		CodeString:        "omecide",
		Description:       "раз в 4 хода дважды плюется ядом в случайные цели, нанося им по 3 урона за ход в течении 3х ходов",
		HealthPoints:      7,
		Attack:            2,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      2,
		ManaCost:          6,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Ядовитый всплеск",
		SkillCode:         "poisonous_splash",
		SkillKind:         SkillKindDebuff,
		SkillTargeting:    SkillTargetEnemyRandomMulti,
		SkillPower:        3,
		SkillBaseCooldown: 4,
		SkillDuration:     3,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: DebuffEffectDamageOverTime,
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   2,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Отравляющее присутствие",
			Code:           "poisonous_presence",
			Description:    "В начале хода наносит 2 урона всему вражескому столу",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerTurnStart,
			EffectKind:     PassiveEffectDamage,
			Target:         SkillTargetEnemyAll,
			Power:          2,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     "",
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    PassiveEventFilterNone,
			EventRace:      "",
			ScaleMode:      PassiveScaleNone,
			IgnoreTank:     true,
		},
	},
	{
		Name:              "Мегацид",
		CodeString:        "megacide",
		Description:       "Раз в 3 хода атакует группу вражеских карт, нанося 6 едениц урона центральной цели",
		HealthPoints:      9,
		Attack:            2,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      2,
		ManaCost:          7,
		MaxCopies:         2,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Плазменный луч",
		SkillCode:         "plasma_beam",
		SkillKind:         SkillKindDamage,
		SkillTargeting:    SkillTargetEnemySplash,
		SkillPower:        6,
		SkillBaseCooldown: 3,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Губитель человечества",
			Code:           "scourge_of_humanity",
			Description:    "Получает +1 к силе своего скилла за каждого Human на столе противника",
			Kind:           PassiveKindAura,
			Trigger:        PassiveTriggerWhileAlive,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectSkillPower,
			DebuffEffect:   "",
			Condition:      PassiveConditionEnemyRaceCount,
			ConditionRace:  Human,
			ConditionValue: 0,
			EventFilter:    PassiveEventFilterNone,
			EventRace:      "",
			ScaleMode:      PassiveScalePerEnemyRaceCount,
			IgnoreTank:     true,
		},
	},
	{
		Name:              "Рапид",
		CodeString:        "rapid",
		Description:       "Раз в 2 накладывает на себя бафф, позволяющий основной атаке отскочить в двух случайых целей противника",
		HealthPoints:      14,
		Attack:            6,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      1,
		ManaCost:          8,
		MaxCopies:         1,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Дикая охота",
		SkillCode:         "wild_hunt",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        0,
		SkillBaseCooldown: 2,
		SkillDuration:     1,
		SkillExtraValue:   2,
		SkillBuffEffect:   BuffEffectChainAttack,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Инстинкты",
			Code:           "instincts",
			Description:    "Получает +1 к атаке за каждую карту на столе противника",
			Kind:           PassiveKindAura,
			Trigger:        PassiveTriggerWhileAlive,
			EffectKind:     PassiveEffectBuff,
			Target:         SkillTargetSelf,
			Power:          1,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectAttack,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    PassiveEventFilterNone,
			EventRace:      "",
			ScaleMode:      PassiveScalePerEnemyUnit,
			IgnoreTank:     true,
		},
	},
	{
		Name:              "Слон",
		CodeString:        "slon",
		Description:       "Призывает собственную копию на стол",
		HealthPoints:      18,
		Attack:            3,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Demonical,
		BaseCooldown:      2,
		ManaCost:          9,
		MaxCopies:         1,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Мы-рой",
		SkillCode:         "we_are_swarm",
		SkillKind:         SkillKindSummon,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        0,
		SkillBaseCooldown: 10,
		SkillDuration:     0,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   1,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Живой щит",
			Code:           "living_shield",
			Description:    "Пока карта жива, повышает ХП всем союзным веспидам на 2",
			Kind:           PassiveKindAura,
			Trigger:        PassiveTriggerWhileAlive,
			Target:         SkillTargetAllyAll,
			EffectKind:     PassiveEffectBuff,
			TargetRace:     Demonical,
			Power:          2,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectHP,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    PassiveEventFilterNone,
			EventRace:      "",
			ScaleMode:      PassiveScaleNone,
			IgnoreTank:     true,
		},
	},
	{
		Name:              "Хормагат",
		CodeString:        "hormagat",
		Description:       "Увеличивает КД атаки группе противника на 2 единицы на 2 хода",
		HealthPoints:      16,
		Attack:            6,
		SplashRadius:      1,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      1,
		ManaCost:          9,
		MaxCopies:         1,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Деморализующее присутствие",
		SkillCode:         "demoralizing_presence",
		SkillKind:         SkillKindDebuff,
		SkillTargeting:    SkillTargetEnemySplash,
		SkillPower:        2,
		SkillBaseCooldown: 5,
		SkillDuration:     2,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: DebuffEffectCooldownUp,
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Древний противник",
			Code:           "ancient_enemy",
			Description:    "При выходе на стол наносит 4 урона всему вражескому столу",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnEnter,
			EffectKind:     PassiveEffectDamage,
			Target:         SkillTargetEnemyAll,
			Power:          4,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     "",
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    PassiveEventFilterNone,
			EventRace:      "",
			ScaleMode:      PassiveScaleNone,
			IgnoreTank:     true,
		},
	},
	{
		Name:              "Альфалиск",
		CodeString:        "alphalisk",
		Description:       "Навсегда фиксирует ХП выбранного существа на 1",
		HealthPoints:      14,
		Attack:            7,
		SplashRadius:      0,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      2,
		ManaCost:          9,
		MaxCopies:         1,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Шокирующий ужас",
		SkillCode:         "shocking_horror",
		SkillKind:         SkillKindHybrid,
		SkillTargeting:    SkillTargetEnemySingle,
		SkillPower:        0,
		SkillBaseCooldown: 5,
		SkillDuration:     0,
		SkillExtraValue:   1,
		SkillBuffEffect:   EffectSetFixedHP,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Опаснейший противник",
			Code:           "deadliest_enemy",
			Description:    "Каждый раз, когда вражеская карта использует способность, наносит 2 урона случайному противнику",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnEnemySkill,
			EffectKind:     PassiveEffectDamage,
			Target:         SkillTargetEnemyRandom,
			Power:          2,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     "",
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    PassiveEventFilterSkillUsed,
			EventRace:      "",
			ScaleMode:      PassiveScaleNone,
			IgnoreTank:     true,
		},
	},
	{
		Name:              "Мегалацид",
		CodeString:        "megalacide",
		Description:       "При активации скилла, после того как атакует противника повышает себе силу атаки на 2 еденицы на 3 хода",
		HealthPoints:      18,
		Attack:            4,
		SplashRadius:      0,
		IsTank:            true,
		CardType:          Demonical,
		BaseCooldown:      1,
		ManaCost:          9,
		MaxCopies:         1,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Постоянный рост",
		SkillCode:         "constant_growth",
		SkillKind:         SkillKindBuff,
		SkillTargeting:    SkillTargetSelf,
		SkillPower:        2,
		SkillBaseCooldown: 2,
		SkillDuration:     3,
		SkillExtraValue:   0,
		SkillBuffEffect:   BuffEffectBonusAfterAttack,
		SkillDebuffEffect: "",
		SkillCleanseMode:  "",
		SkillIgnoreTank:   false,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Вестник роя",
			Code:           "herald_of_swarm",
			Description:    "Когда получает урон, немедленно атакует нападавшего своей основной атакой",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnDamaged,
			EffectKind:     PassiveEffectCounterattack,
			Target:         SkillTargetAttackTarget,
			Power:          0,
			Duration:       0,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     BuffEffectCounterattack,
			DebuffEffect:   "",
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    PassiveEventFilterNone,
			EventRace:      "",
			ScaleMode:      PassiveScaleNone,
			IgnoreTank:     true,
		},
	},
	{
		Name:              "Левиафан",
		CodeString:        "leviathan",
		Description:       "На 3 хода делает всех противников восприимчивее к урону на 2 единицы",
		HealthPoints:      22,
		Attack:            8,
		SplashRadius:      1,
		IsTank:            false,
		CardType:          Demonical,
		BaseCooldown:      3,
		ManaCost:          10,
		MaxCopies:         1,
		ImageKey:          "",
		AssetBaseKey:      "",
		SkillImageKey:     "",
		HasSkill:          true,
		SkillName:         "Оглушительный рев",
		SkillCode:         "deafening_roar",
		SkillKind:         SkillKindDebuff,
		SkillTargeting:    SkillTargetEnemyAll,
		SkillPower:        2,
		SkillBaseCooldown: 3,
		SkillDuration:     3,
		SkillExtraValue:   0,
		SkillBuffEffect:   "",
		SkillDebuffEffect: DebuffEffectVulnerable,
		SkillCleanseMode:  "",
		SkillIgnoreTank:   true,
		SkillApplyCount:   0,
		HasPassive:        true,
		Passive: PassiveSpec{
			Name:           "Гибельное заражение",
			Code:           "fatal_infection",
			Description:    "При смерти накладывает на весь вражеский стол дебаф на 3 хода, наносящий 3 единицы урона",
			Kind:           PassiveKindReactive,
			Trigger:        PassiveTriggerOnLeave,
			EffectKind:     PassiveEffectDebuff,
			Target:         SkillTargetEnemyAll,
			Power:          3,
			Duration:       3,
			ExtraValue:     0,
			ApplyCount:     0,
			BuffEffect:     "",
			DebuffEffect:   DebuffEffectDamageOverTime,
			Condition:      PassiveConditionNone,
			ConditionRace:  "",
			ConditionValue: 0,
			EventFilter:    PassiveEventFilterNone,
			EventRace:      "",
			ScaleMode:      PassiveScaleNone,
			IgnoreTank:     true,
		},
	},
}

/*По аналогии с картами, это стандартное описание всех возможных бафф карт, которые есть в игре (так же будут платные)
Как ты можешь увидеть здесь все работает по схожему принципу, за исключением того, что у баф карт очевидно не может
быть силы атаки, кд и всего того, что может бить, стрелять и производить действия на поле боя. Так вот...*/
var DefaultBuffCards = []BuffCardsTemplate{}
