package cards

/*Описание дефолтных карт. В будущем будут и донатные, но сейчас речь не об этом. Здесь в общем то сердце
всех карт, которые были, есть и будут. Как уже говорилось в описании констант, у каждой карты есть свое
уникальное имя, код (для операционки), хп, атака и все то, что увидишьт внутри описания. Так вот, важно
здесь не то, что и ежу понятно (в роли атаки, хп), а такие штуки как BuffSlot->который отвечает за то, можно
ли улучшить карту, MaxCopies->который отвечает за то, сколько карт конкретного типа можно взять в матч.
Сделано чисто на тот вариант, чтобы игрок не мог с собой взять все 20 карт одной и той же масти, если можно
так сказать конечно. К слову это и сидится вместе с миграциями в моем замечательном пакете bootstrap.*/

/*
В игре представлены (пока что) 3 расы: Империя, Демоны и ИИ технологии. Есть так же три категории карт:
Треш(множественные карты, которые играются массово, они дешевые и не наносят большой урон, так же как и
не обладают большим количеством ХП), Средние карты (Серьезные боевые карты под ту. Обладают хорошими
характеристиками. Стоят средне. В общем, средняя боевая еденица на поле боя) и Ультимативные (самые дорогие
карты в игре(так же карта может быть средней по стоимости, но быть энивей ультимативной). Такие карты имеют
самые крутые статы, но и стоят лошадиных денег)
*/

var DefaultBattleCards = []BattleCardTemplate{
	{
		/*ВОЙСКА ИМПЕРИИ*/
		//Обычная пехота империи. Трэш
		Name:            "Имперский пехотинец", //<-имя карты
		CodeString:      "imperial_guardian",   //<-код карты для простого обращения к нему. Используется в операционке
		HealthPoints:    30,                    //<-хп карты
		Attack:          15,                    //<-сила атаки карты
		SplashRadius:    0,
		IsTank:          false,         //<-является ли карта танком (это вообще отдельный разговор)
		CardType:        OrganicalCard, //<-тип карты, нужен для бафов и прочей ерунды
		CoolDown:        0,             //<-кд атаки карты. Если значение 1-значит карта может бить только через ход
		ManaCost:        1,             //<-стоимость карты в мане
		BuffSlot:        true,          //<-есть ли возможность  улучшить карту с помощью бафа
		MaxCopies:       5,             //<-максимально допустимое количество копий, которое игрок может взять в матч
		Description:     "",            //<-описание. Используется для UI, чтобы игрок смог прочесть че вообще за карта
		ImageKey:        "",            //<-ключ картинки, которая отражает то, как выглядит карта
		AssetBaseKey:    "",            //<-а здесь будут храниться ключи анимации (вообще отдельная тема)
		SkillName:       "Осколочные гранаты",
		SkillCode:       SkillDamageSplash,
		SkillTrigger:    TriggerActive,
		SkillTarget:     TargetEnemySplash,
		SkillValue:      10,
		SkillDuration:   0,
		SkillCooldown:   2,
		SkillParamsJSON: "",
	},
	{
		//пехота с пулеметами. Средняя
		Name:            "Пулеметное отделение",
		CodeString:      "machine_gun_crew",
		HealthPoints:    30,
		Attack:          25,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        OrganicalCard,
		CoolDown:        0,
		ManaCost:        2,
		BuffSlot:        true,
		MaxCopies:       3,
		SkillName:       "Крупнокалиберные боеприпасы",
		SkillCode:       SkillApplyBuff,
		SkillTrigger:    TriggerActive,
		SkillTarget:     TargetSelf,
		SkillValue:      10,
		SkillDuration:   2,
		SkillCooldown:   3,
		SkillParamsJSON: "",
	},
	{
		//снайперы. Это вообще ультимативная за свои деньги
		Name:            "Снайперы",
		CodeString:      "snipers",
		HealthPoints:    20,
		Attack:          45,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        OrganicalCard,
		CoolDown:        1,
		ManaCost:        5,
		BuffSlot:        true,
		MaxCopies:       2,
		SkillName:       "Устранение",
		SkillCode:       SkillDamageSingle,
		SkillTrigger:    TriggerActive,
		SkillTarget:     TargetEnemyUnit,
		SkillValue:      40,
		SkillDuration:   0,
		SkillCooldown:   5,
		SkillParamsJSON: "ignore_tank=true",
	},
	{
		//пехота с гранатометами. Средняя карта
		Name:            "Гранатометное отделение",
		CodeString:      "mortar_crew",
		HealthPoints:    25,
		Attack:          20,
		SplashRadius:    1,
		IsTank:          false,
		CardType:        OrganicalCard,
		CoolDown:        1,
		ManaCost:        4,
		BuffSlot:        true,
		MaxCopies:       3,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//Ульта. Лютый чел со всем возможным вооружением и медведем, к которому привязаны установки с бпла
		Name:            "Лесник",
		CodeString:      "forester",
		HealthPoints:    70,
		Attack:          40,
		SplashRadius:    1,
		IsTank:          false,
		CardType:        OrganicalCard,
		CoolDown:        0,
		ManaCost:        7,
		BuffSlot:        true,
		MaxCopies:       1,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//серьезная пехота с экзоскелетами. Серьезное вооружение. Ульта
		Name:            "Десант",
		CodeString:      "paratroopers",
		HealthPoints:    50,
		Attack:          30,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        OrganicalCard,
		CoolDown:        0,
		ManaCost:        6,
		BuffSlot:        true,
		MaxCopies:       5,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//серьезная пехота в стальной броне и внушительным вооружением. Средняя
		Name:            "Имперские штурмовики",
		CodeString:      "imperial_stormtroopers",
		HealthPoints:    80,
		Attack:          30,
		SplashRadius:    0,
		IsTank:          true,
		CardType:        OrganicalCard,
		CoolDown:        0,
		ManaCost:        6,
		BuffSlot:        true,
		MaxCopies:       3,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//серьезная пехота в стальной броне и крупнокалиберными пулеметами. Ульта
		Name:            "Имперские гвардейцы",
		CodeString:      "imperial_guadians",
		HealthPoints:    80,
		Attack:          40,
		SplashRadius:    0,
		IsTank:          true,
		CardType:        OrganicalCard,
		CoolDown:        0,
		ManaCost:        7,
		BuffSlot:        true,
		MaxCopies:       3,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//робот с двумя щитами и крупнокалиберным пулеметом. Средняя
		Name:            "Механический рыцарь",
		CodeString:      "mechanical_knight",
		HealthPoints:    80,
		Attack:          15,
		SplashRadius:    0,
		IsTank:          true,
		CardType:        MechanicalCard,
		CoolDown:        1,
		ManaCost:        3,
		BuffSlot:        true,
		MaxCopies:       3,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//бпла с ракетой на борту. Треш
		Name:            "БПЛА СОКОЛ",
		CodeString:      "drones",
		HealthPoints:    20,
		Attack:          15,
		SplashRadius:    1,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        1,
		ManaCost:        2,
		BuffSlot:        true,
		MaxCopies:       4,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//взвод из танков. Средняя
		Name:            "Танковый взвод",
		CodeString:      "tank_platoon",
		HealthPoints:    100,
		Attack:          40,
		SplashRadius:    0,
		IsTank:          true,
		CardType:        MechanicalCard,
		CoolDown:        1,
		ManaCost:        4,
		BuffSlot:        true,
		MaxCopies:       3,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//бронебойные БПЛА. Средняя
		Name:            "БПЛА ТАЙФУН",
		CodeString:      "armor_piercing_drones",
		HealthPoints:    20,
		Attack:          25,
		SplashRadius:    1,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        1,
		ManaCost:        5,
		BuffSlot:        true,
		MaxCopies:       3,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//группа ударных вертолетов. Средняя
		Name:            "Аллигаторы",
		CodeString:      "alligators",
		HealthPoints:    50,
		Attack:          65,
		SplashRadius:    1,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        1,
		ManaCost:        6,
		BuffSlot:        true,
		MaxCopies:       2,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//самый современный истребитель армии РФ. Ульта
		Name:            "СУ57",
		CodeString:      "su-57",
		HealthPoints:    60,
		Attack:          90,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        1,
		ManaCost:        7,
		BuffSlot:        true,
		MaxCopies:       2,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//группа БТР. Механический треш
		Name:            "Группа БТР",
		CodeString:      "btr_crew",
		HealthPoints:    40,
		Attack:          30,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        0,
		ManaCost:        4,
		BuffSlot:        true,
		MaxCopies:       4,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//механеический треш через урон по всему полю
		Name:            "МСТА-С",
		CodeString:      "msta_s",
		HealthPoints:    40,
		Attack:          20,
		SplashRadius:    5,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        2,
		ManaCost:        3,
		BuffSlot:        true,
		MaxCopies:       3,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//мехническая ульта. огромный робот, который больно бьет
		Name:            "Святогор",
		CodeString:      "svyatogor",
		HealthPoints:    240,
		Attack:          110,
		SplashRadius:    1,
		IsTank:          true,
		CardType:        MechanicalCard,
		CoolDown:        0,
		ManaCost:        10,
		BuffSlot:        true,
		MaxCopies:       1,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//механическая ульта 2. Огромный самолет, контролирующий БПЛА
		Name:            "Белый лебедь",
		CodeString:      "white_swann",
		HealthPoints:    100,
		Attack:          50,
		SplashRadius:    5,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        1,
		ManaCost:        10,
		BuffSlot:        true,
		MaxCopies:       2,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},

	/*ВОЙСКА ДЕМОНОВ*/
	//далее демоны. Их прикол чисто в массовости. Но у них есть и очень сильные карты

	{
		//треш, урон в соло. Много их
		Name:            "Гончие пепла",
		CodeString:      "ash_hound",
		HealthPoints:    20,
		Attack:          15,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        DemonicalCard,
		CoolDown:        0,
		ManaCost:        2,
		BuffSlot:        true,
		MaxCopies:       5,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//толпа одержимых демонами людей. Треш.
		Name:            "Одержимые",
		CodeString:      "obsessed",
		HealthPoints:    20,
		Attack:          15,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        OrganicalCard,
		CoolDown:        0,
		ManaCost:        1,
		BuffSlot:        true,
		MaxCopies:       5,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//толпа восставших солдат, убитых в разное время. Треш
		Name:            "Восставшая рота",
		CodeString:      "rebellous_company",
		HealthPoints:    30,
		Attack:          10,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        OrganicalCard,
		CoolDown:        0,
		ManaCost:        1,
		BuffSlot:        true,
		MaxCopies:       4,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//толпа восставших солдат с войн посовременнее. Треш
		Name:            "Поверженные",
		CodeString:      "defeated",
		HealthPoints:    30,
		Attack:          15,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        OrganicalCard,
		CoolDown:        0,
		ManaCost:        2,
		BuffSlot:        true,
		MaxCopies:       4,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//свора проклятых собак. Злой треш
		Name:            "Проклятая свора",
		CodeString:      "cursed_pack",
		HealthPoints:    25,
		Attack:          20,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        OrganicalCard,
		CoolDown:        0,
		ManaCost:        2,
		MaxCopies:       4,
		SkillName:       "Рваные раны",
		SkillCode:       SkillApplyDebuff,
		SkillTrigger:    TriggerActive,
		SkillTarget:     TargetEnemyUnit,
		SkillValue:      5,
		SkillDuration:   3,
		SkillCooldown:   3,
		SkillParamsJSON: "",
	},
	{
		//треш, урон на пол стола
		Name:            "Обожженные голуби",
		CodeString:      "burned_pigeons",
		HealthPoints:    20,
		Attack:          15,
		SplashRadius:    1,
		IsTank:          false,
		CardType:        OrganicalCard,
		CoolDown:        0,
		ManaCost:        2,
		MaxCopies:       4,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//демон кастующий огненный ливень. Треш
		Name:            "Вестник пепла",
		CodeString:      "harbinger_fire",
		HealthPoints:    15,
		Attack:          20,
		SplashRadius:    1,
		IsTank:          false,
		CardType:        DemonicalCard,
		CoolDown:        1,
		ManaCost:        2,
		BuffSlot:        false,
		MaxCopies:       4,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//демон, из которого выползают демоны поменьше. Треш
		Name:            "Тварь поганая",
		CodeString:      "filthy_creature",
		HealthPoints:    40,
		Attack:          10,
		SplashRadius:    1,
		IsTank:          true,
		CardType:        DemonicalCard,
		CoolDown:        0,
		ManaCost:        3,
		BuffSlot:        true,
		MaxCopies:       4,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//здоровый паук, который выпускает паучков поменьше. Средняя
		Name:            "Шипастые пауки",
		CodeString:      "spiny_spiders",
		HealthPoints:    40,
		Attack:          25,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        DemonicalCard,
		CoolDown:        0,
		ManaCost:        4,
		BuffSlot:        true,
		MaxCopies:       3,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//за свои бабки ультимативная. Бьет по всему столу на нихуевый дамаг. Минус один -кд
		Name:            "Собиратель душ",
		CodeString:      "collector_of_souls",
		HealthPoints:    50,
		Attack:          25,
		SplashRadius:    5,
		IsTank:          false,
		CardType:        DemonicalCard,
		CoolDown:        2,
		ManaCost:        6,
		BuffSlot:        true,
		MaxCopies:       2,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//средняя карта. Большой монстр с крыльями. Пойдет
		Name:            "Крылатый разоритель",
		CodeString:      "winged_destroyer",
		HealthPoints:    40,
		Attack:          25,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        DemonicalCard,
		CoolDown:        0,
		ManaCost:        5,
		BuffSlot:        true,
		MaxCopies:       3,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//за свои бабки пиздец. Одновременно и танк и дд. Ульта
		Name:            "Проклятый зверь",
		CodeString:      "cursed_beast",
		HealthPoints:    75,
		Attack:          35,
		SplashRadius:    0,
		IsTank:          true,
		CardType:        DemonicalCard,
		CoolDown:        0,
		ManaCost:        5,
		BuffSlot:        false,
		MaxCopies:       2,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//танк. Большой тролль с большим мечом. Средняя
		Name:            "Лентяй",
		CodeString:      "lazy",
		HealthPoints:    100,
		Attack:          25,
		SplashRadius:    1,
		IsTank:          true,
		CardType:        DemonicalCard,
		CoolDown:        0,
		ManaCost:        5,
		BuffSlot:        true,
		MaxCopies:       2,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//Большой двухголовый огр. Не является танком несмотря на внушительные хп. Средняя
		Name:            "Огр",
		CodeString:      "ogre",
		HealthPoints:    120,
		Attack:          45,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        DemonicalCard,
		CoolDown:        0,
		ManaCost:        7,
		BuffSlot:        true,
		MaxCopies:       2,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//ультимативный танк за свои деньги. Основной прикол в хп
		Name:            "Мразь",
		CodeString:      "scum",
		HealthPoints:    200,
		Attack:          40,
		SplashRadius:    1,
		IsTank:          true,
		CardType:        DemonicalCard,
		CoolDown:        1,
		ManaCost:        8,
		BuffSlot:        false,
		MaxCopies:       2,
		SkillName:       "Разложение",
		SkillCode:       SkillIncEnemyCdAllOnDeath,
		SkillTrigger:    TriggerOnDeath,
		SkillTarget:     TargetEnemyAll,
		SkillValue:      2,
		SkillDuration:   2,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//ультимативная. Смысл в большом дамаге
		Name:            "Демонический берсерк",
		CodeString:      "demonic_berserker",
		HealthPoints:    100,
		Attack:          55,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        DemonicalCard,
		CoolDown:        0,
		ManaCost:        8,
		BuffSlot:        true,
		MaxCopies:       2,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//средняя карта. Можно сказать треш на высоком уровне маны
		Name:            "Хозяйка зверей",
		CodeString:      "mistress_of_the_beasts",
		HealthPoints:    90,
		Attack:          55,
		SplashRadius:    0,
		IsTank:          true,
		CardType:        DemonicalCard,
		CoolDown:        0,
		ManaCost:        8,
		BuffSlot:        true,
		MaxCopies:       2,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//средняя карта. Танк, который бьет по сплешу
		Name:            "Безумный палач",
		CodeString:      "mad_executioner",
		HealthPoints:    150,
		Attack:          40,
		SplashRadius:    1,
		IsTank:          true,
		CardType:        DemonicalCard,
		CoolDown:        1,
		ManaCost:        8,
		BuffSlot:        true,
		MaxCopies:       2,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//средняя карта. Огромные великаны с небольшим уроном, но очень большим хп
		Name:            "Пепельные великаны",
		CodeString:      "ash_giants",
		HealthPoints:    200,
		Attack:          30,
		SplashRadius:    0,
		IsTank:          true,
		CardType:        DemonicalCard,
		CoolDown:        0,
		ManaCost:        9,
		BuffSlot:        true,
		MaxCopies:       2,
		SkillName:       "Ужас",
		SkillCode:       "inc_enemy_cd_single",
		SkillTrigger:    TriggerActive,
		SkillTarget:     TargetEnemyUnit,
		SkillValue:      2,
		SkillDuration:   3,
		SkillCooldown:   5,
		SkillParamsJSON: "",
	},
	{
		//ультимативная карта. Прям пиздец. Огромный размером с 40 этажный дом цербер
		Name:            "Цербер",
		CodeString:      "cerber",
		HealthPoints:    300,
		Attack:          70,
		SplashRadius:    1,
		IsTank:          true,
		CardType:        DemonicalCard,
		CoolDown:        1,
		ManaCost:        10,
		BuffSlot:        false,
		MaxCopies:       1,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//средняя карта. Отличается как хп так и уроном
		Name:            "Господин демонов",
		CodeString:      "lord_of_demons",
		HealthPoints:    180,
		Attack:          50,
		SplashRadius:    0,
		IsTank:          true,
		CardType:        DemonicalCard,
		CoolDown:        0,
		ManaCost:        10,
		BuffSlot:        true,
		MaxCopies:       1,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//ультимативная. Самая сильная карта демонов
		Name:            "Первородный демон",
		CodeString:      "primordial_demon",
		HealthPoints:    220,
		Attack:          85,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        DemonicalCard,
		CoolDown:        0,
		ManaCost:        10,
		BuffSlot:        false,
		MaxCopies:       1,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},

	/*ВОЙСКА ИИ*/
	// далее ИИ карты. Их основной принцип в том, что раскрываются карты в поздней игре, когда много маны

	{
		//треш карта. По сути одно колесо, начиненное взрывчаткой
		Name:            "Моудль: ШТУРМ",
		CodeString:      "modul_strom",
		HealthPoints:    15,
		Attack:          20,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        0,
		ManaCost:        1,
		BuffSlot:        true,
		MaxCopies:       5,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//треш карта. Небольшие роботы с крупнокалиберными пулеметами
		Name:            "Модуль: ЗАЧИСТКА",
		CodeString:      "modul_cleanup",
		HealthPoints:    20,
		Attack:          15,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        0,
		ManaCost:        1,
		BuffSlot:        true,
		MaxCopies:       5,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//хорошая средняя карта. Небольшой робот с ракетами на борту
		Name:            "Модуль: ЗАЛП",
		CodeString:      "modul_volley",
		HealthPoints:    20,
		Attack:          15,
		SplashRadius:    1,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        0,
		ManaCost:        3,
		BuffSlot:        true,
		MaxCopies:       5,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//группа БПЛА со стволами на борту. Средняя
		Name:            "Модуль: РОЙ",
		CodeString:      "modul_swarm",
		HealthPoints:    20,
		Attack:          25,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        0,
		ManaCost:        3,
		BuffSlot:        true,
		MaxCopies:       5,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//средняя карта. Робот с пулеметами на борту. Отличается уроном
		Name:            "Модуль: ШКВАЛ",
		CodeString:      "modul_squall",
		HealthPoints:    30,
		Attack:          30,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        0,
		ManaCost:        6,
		BuffSlot:        true,
		MaxCopies:       3,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//безпилотный веротлет со средним вооружением. Средняя
		Name:            "Модуль: ПОКРЫТИЕ",
		CodeString:      "modul_coating",
		HealthPoints:    50,
		Attack:          40,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        0,
		ManaCost:        6,
		BuffSlot:        true,
		MaxCopies:       3,
		SkillName:       "Сканирование местности",
		SkillCode:       SkillRevealEnemyHand,
		SkillTrigger:    TriggerActive,
		SkillTarget:     TargetNone,
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   5,
		SkillParamsJSON: "",
	},
	{
		//огромный вертолет с вооружением и БПЛА на борту. Средняя
		Name:            "Модуль: ПЛАТФОРМА",
		CodeString:      "modul_platform",
		HealthPoints:    40,
		Attack:          60,
		SplashRadius:    1,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        1,
		ManaCost:        6,
		BuffSlot:        true,
		MaxCopies:       2,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//безпилотный истребитель. Средняя карта
		Name:            "Модуль: ПЕРЕХВАТ",
		CodeString:      "modul_interception",
		HealthPoints:    70,
		Attack:          70,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        1,
		ManaCost:        7,
		BuffSlot:        true,
		MaxCopies:       2,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//безпилотный истребитель. На борту ракета КИНЖАЛ. Ультимативная
		Name:            "Модуль: ВЕКТОР",
		CodeString:      "modul_vector",
		HealthPoints:    70,
		Attack:          100,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        1,
		ManaCost:        8,
		BuffSlot:        true,
		MaxCopies:       2,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//ультимативная. Баллистическая ракета по сути
		Name:            "Модуль: ЗАПУСК",
		CodeString:      "modul_start",
		HealthPoints:    50,
		Attack:          80,
		SplashRadius:    1,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        2,
		ManaCost:        8,
		BuffSlot:        true,
		MaxCopies:       2,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//ультимативная, потому что не имеет КД. Безпилотный дрон с самонаводящимися ракетами на борту
		Name:            "Модуль: УСТРАНЕНИЕ",
		CodeString:      "modul_elimination",
		HealthPoints:    80,
		Attack:          40,
		SplashRadius:    1,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        0,
		ManaCost:        8,
		BuffSlot:        true,
		MaxCopies:       2,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//средняя карта. Рой дронов с бомбами на борту. Хуярит весь стол
		Name:            "Модуль: ДОМИНАЦИЯ",
		CodeString:      "modul_domination",
		HealthPoints:    30,
		Attack:          20,
		SplashRadius:    5,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        1,
		ManaCost:        8,
		BuffSlot:        true,
		MaxCopies:       3,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//средняя карта. Ахуенный безпилотный БТР
		Name:            "Модуль: БАСТИОН",
		CodeString:      "modul_bastion",
		HealthPoints:    80,
		Attack:          30,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        0,
		ManaCost:        7,
		BuffSlot:        true,
		MaxCopies:       3,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//ультимативная. Тяжелый танк с подконтрольным ему роем дронов
		Name:            "Модуль: СЕТЬ",
		CodeString:      "modul_web",
		HealthPoints:    120,
		Attack:          55,
		SplashRadius:    1,
		IsTank:          true,
		CardType:        MechanicalCard,
		CoolDown:        1,
		ManaCost:        8,
		BuffSlot:        true,
		MaxCopies:       2,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//ультимативная. Огромный безпилотный бомбордировщик
		Name:            "Модуль: ТЕНЬ",
		CodeString:      "modul_shadow",
		HealthPoints:    50,
		Attack:          70,
		SplashRadius:    5,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        1,
		ManaCost:        10,
		BuffSlot:        true,
		MaxCopies:       2,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//ультимативная пиздец. Огромный бомбордировщик с ядерными ракетами на борту
		Name:            "Модуль: ПРЕВОСХОДСТВО",
		CodeString:      "modul_superiority",
		HealthPoints:    70,
		Attack:          120,
		SplashRadius:    2,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        2,
		ManaCost:        10,
		BuffSlot:        true,
		MaxCopies:       2,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//огромнейший дрон с подключенным к нему роем дроном. Ультимативнейшая
		Name:            "Модуль: КАСКАД",
		CodeString:      "modul_cascade",
		HealthPoints:    50,
		Attack:          40,
		SplashRadius:    5,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        0,
		ManaCost:        10,
		BuffSlot:        true,
		MaxCopies:       1,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//развеывательная станция. Рядом с ней шахты с балистическими ракетами. Ультимативнейшая
		Name:            "Модуль: ОРБИТА",
		CodeString:      "modul_orbit",
		HealthPoints:    30,
		Attack:          120,
		SplashRadius:    5,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        1,
		ManaCost:        10,
		BuffSlot:        true,
		MaxCopies:       1,
		SkillName:       "Периметр",
		SkillCode:       SkillBanishUnit,
		SkillTrigger:    TriggerOnDeath,
		SkillTarget:     TargetEnemyUnit,
		SkillValue:      100,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
	{
		//ультимативнейшая. Летающая тарелка нахуй, что еще говорить ?
		Name:            "Модуль: АБСТОЛЮТ",
		CodeString:      "modul_absolute",
		HealthPoints:    130,
		Attack:          80,
		SplashRadius:    0,
		IsTank:          false,
		CardType:        MechanicalCard,
		CoolDown:        1,
		ManaCost:        10,
		BuffSlot:        true,
		MaxCopies:       1,
		SkillName:       "",
		SkillCode:       "",
		SkillTrigger:    "",
		SkillTarget:     "",
		SkillValue:      0,
		SkillDuration:   0,
		SkillCooldown:   0,
		SkillParamsJSON: "",
	},
}

/*По аналогии с картами, это стандартное описание всех возможных бафф карт, которые есть в игре (так же будут платные)
Как ты можешь увидеть здесь все работает по схожему принципу, за исключением того, что у баф карт очевидно не может
быть силы атаки, кд и всего того, что может бить, стрелять и производить действия на поле боя. Так вот...*/
var DefaultBuffCards = []BuffCardsTemplate{
	{
		Name:         "Адреналин",   //<-имя
		CodeString:   "adrenalin",   //<-уникальный код карты
		ManaCost:     1,             //<-стоимость в мане
		BuffType:     DamageUpdate,  //<-тип улучшения
		BuffValue:    7,             //<-число, на которое баф увеличивает то, или иное значение карты
		OnlyFor:      OrganicalCard, //<-то, к какому типу карт можно применить баф (в случае адреналина только к органическим картам)
		MaxCopies:    4,             //<-максимально допустимое количество копий одной карты в матче
		Duration:     1,             //<-длительность бафа. Если значение 0-баф постоянный. Если значение 1-баф действует 1 ход и далее
		Description:  "",            //<-описание для UI
		ImageKey:     "",            //<-картинка. Тоже для UI
		AssetBaseKey: "",            //<-и ключи анимаций соответственно
	},
	{
		Name:       "Линейный привод",
		CodeString: "linear_actuator",
		ManaCost:   2,
		BuffType:   DamageUpdate,
		BuffValue:  3,
		OnlyFor:    MechanicalCard,
		MaxCopies:  3,
		Duration:   1,
	},
	{
		Name:       "Обновление процессоров",
		CodeString: "processor_update",
		ManaCost:   3,
		BuffType:   CoolDownUpdate,
		BuffValue:  1,
		OnlyFor:    MechanicalCard,
		MaxCopies:  2,
		Duration:   2,
	},
	{
		Name:       "Новая военная доктрина",
		CodeString: "new_war_doctrine",
		ManaCost:   10,
		BuffType:   DamageUpdate,
		BuffValue:  10,
		OnlyFor:    All,
		MaxCopies:  1,
		Duration:   0,
	},
	{
		Name:       "Подкрепление",
		CodeString: "reinforcement",
		ManaCost:   4,
		BuffType:   HealthPointsUpdate,
		BuffValue:  10,
		OnlyFor:    All,
		MaxCopies:  3,
		Duration:   0,
	},
	{
		Name:       "Логистическая цепочка",
		CodeString: "supply_chain",
		ManaCost:   3,
		BuffType:   HealthPointsUpdate,
		BuffValue:  5,
		OnlyFor:    All,
		MaxCopies:  2,
		Duration:   0,
	},
	{
		Name:       "Демоническое присутствие",
		CodeString: "demonical_presence",
		ManaCost:   2,
		BuffType:   DamageUpdate,
		BuffValue:  7,
		OnlyFor:    DemonicalCard,
		MaxCopies:  5,
		Duration:   3,
	},
	{
		Name:       "Темное причастие",
		CodeString: "dark_communion",
		ManaCost:   4,
		BuffType:   DamageUpdate,
		BuffValue:  8,
		OnlyFor:    DemonicalCard,
		MaxCopies:  2,
		Duration:   3,
	},
	{
		Name:       "Замена процессоров",
		CodeString: "replacing_processors",
		ManaCost:   5,
		BuffType:   DamageUpdate,
		BuffValue:  10,
		OnlyFor:    MechanicalCard,
		MaxCopies:  2,
		Duration:   3,
	},
}
